#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: bp_wi_OptionsVoice

#include "Basic.hpp"

#include "SlateCore_structs.hpp"


namespace SDK::Params
{

// Function bp_wi_OptionsVoice.bp_wi_OptionsVoice_C.ExecuteUbergraph_bp_wi_OptionsVoice
// 0x0400 (0x0400 - 0x0000)
struct bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ECheckBoxState                                Temp_byte_Variable;                                // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(const class FString& InputDeviceId)> K2Node_CreateDelegate_OutputDelegate;              // 0x0008(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void(const class FString& OutputDeviceId)> K2Node_CreateDelegate_OutputDelegate_1;            // 0x0018(0x0010)(ZeroConstructor, NoDestructor)
	class FString                                 K2Node_CustomEvent_Active_Output_Id;               // 0x0028(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 K2Node_CustomEvent_Option;                         // 0x0038(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class ULocalSettings*                         CallFunc_GetVivoxSettings_LocalSettings;           // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 K2Node_CustomEvent_InputDeviceId_2;                // 0x0050(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0060(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_61[0x7];                                       // 0x0061(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ULocalSettings*                         CallFunc_GetVivoxSettings_LocalSettings_1;         // 0x0068(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 K2Node_CustomEvent_InputDeviceId_1;                // 0x0070(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class ULocalSettings*                         CallFunc_GetVivoxSettings_LocalSettings_2;         // 0x0080(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 K2Node_CustomEvent_InputDeviceId;                  // 0x0088(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class ULocalSettings*                         CallFunc_GetVivoxSettings_LocalSettings_3;         // 0x0098(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 K2Node_CustomEvent_OutputDeviceId_2;               // 0x00A0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class ULocalSettings*                         CallFunc_GetVivoxSettings_LocalSettings_4;         // 0x00B0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 K2Node_CustomEvent_OutputDeviceId_1;               // 0x00B8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class ULocalSettings*                         CallFunc_GetVivoxSettings_LocalSettings_5;         // 0x00C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 K2Node_CustomEvent_OutputDeviceId;                 // 0x00D0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	ECheckBoxState                                Temp_byte_Variable_1;                              // 0x00E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_E1[0x7];                                       // 0x00E1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ULocalSettings*                         CallFunc_GetVivoxSettings_LocalSettings_6;         // 0x00E8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x00F0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_F1[0x7];                                       // 0x00F1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TMap<class FString, class FString>            CallFunc_GetAvailableOutputDevices_DeviceIdToName; // 0x00F8(0x0050)()
	class ULocalSettings*                         CallFunc_GetVivoxSettings_LocalSettings_7;         // 0x0148(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_2;                    // 0x0150(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_151[0x7];                                      // 0x0151(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TMap<class FString, class FString>            CallFunc_GetAvailableInputDevices_DeviceidToName;  // 0x0158(0x0050)()
	class ULocalSettings*                         CallFunc_GetVivoxSettings_LocalSettings_8;         // 0x01A8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_3;                    // 0x01B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1B1[0x7];                                      // 0x01B1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_GetEffectiveOutputDeviceId_ReturnValue;   // 0x01B8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class ULocalSettings*                         CallFunc_GetVivoxSettings_LocalSettings_9;         // 0x01C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_4;                    // 0x01D0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1D1[0x3];                                      // 0x01D1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(const class FString& OutputDeviceId)> K2Node_CreateDelegate_OutputDelegate_2;            // 0x01D4(0x0010)(ZeroConstructor, NoDestructor)
	uint8                                         Pad_1E4[0x4];                                      // 0x01E4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class ULocalSettings*                         CallFunc_GetVivoxSettings_LocalSettings_10;        // 0x01E8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ULocalSettings*                         CallFunc_GetVivoxSettings_LocalSettings_11;        // 0x01F0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_GetEffectiveInputDeviceId_ReturnValue;    // 0x01F8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_GetEffectiveInputDeviceId_ReturnValue_1;  // 0x0208(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class ULocalSettings*                         CallFunc_GetVivoxSettings_LocalSettings_12;        // 0x0218(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ULocalSettings*                         CallFunc_GetVivoxSettings_LocalSettings_13;        // 0x0220(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_GetEffectiveOutputDeviceId_ReturnValue_1; // 0x0228(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_GetEffectiveOutputDeviceId_ReturnValue_2; // 0x0238(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class ULocalSettings*                         CallFunc_GetVivoxSettings_LocalSettings_14;        // 0x0248(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ULocalSettings*                         CallFunc_GetVivoxSettings_LocalSettings_15;        // 0x0250(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_5;                    // 0x0258(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_259[0x7];                                      // 0x0259(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_GetEffectiveOutputDeviceId_ReturnValue_3; // 0x0260(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_GetEffectiveInputDeviceId_ReturnValue_2;  // 0x0270(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class ULocalSettings*                         CallFunc_GetVivoxSettings_LocalSettings_16;        // 0x0280(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetOutputGain_ReturnValue;                // 0x0288(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_28C[0x4];                                      // 0x028C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class ULocalSettings*                         CallFunc_GetVivoxSettings_LocalSettings_17;        // 0x0290(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Conv_IntToFloat_ReturnValue;              // 0x0298(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x029C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_29D[0x3];                                      // 0x029D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(const class FString& InputDeviceId)> K2Node_CreateDelegate_OutputDelegate_3;            // 0x02A0(0x0010)(ZeroConstructor, NoDestructor)
	bool                                          K2Node_ComponentBoundEvent_IsChecked;              // 0x02B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2B1[0x7];                                      // 0x02B1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ULocalSettings*                         CallFunc_GetVivoxSettings_LocalSettings_18;        // 0x02B8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ULocalSettings*                         CallFunc_GetVivoxSettings_LocalSettings_19;        // 0x02C0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_6;                    // 0x02C8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2C9[0x3];                                      // 0x02C9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_GetInputVolumeGain_ReturnValue;           // 0x02CC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Conv_IntToFloat_ReturnValue_1;            // 0x02D0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetValue_ReturnValue;                     // 0x02D4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_FTrunc_ReturnValue;                       // 0x02D8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_SetInputVolumeGain_ReturnValue;           // 0x02DC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2DD[0x3];                                      // 0x02DD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_GetValue_ReturnValue_1;                   // 0x02E0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_FTrunc_ReturnValue_1;                     // 0x02E4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsConsolePlatform_ReturnValue;            // 0x02E8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_SetOutputGain_ReturnValue;                // 0x02E9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2EA[0x6];                                      // 0x02EA(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UVivoxLocalPlayer*                      CallFunc_GetLocalPlayerSubsystem_ReturnValue;      // 0x02F0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_7;                    // 0x02F8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2F9[0x3];                                      // 0x02F9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(const class FString& InputDeviceId)> K2Node_CreateDelegate_OutputDelegate_4;            // 0x02FC(0x0010)(ZeroConstructor, NoDestructor)
	uint8                                         Pad_30C[0x4];                                      // 0x030C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class ULocalSettings*                         CallFunc_GetVivoxSettings_LocalSettings_20;        // 0x0310(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_8;                    // 0x0318(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_319[0x7];                                      // 0x0319(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ULocalSettings*                         CallFunc_GetVivoxSettings_LocalSettings_21;        // 0x0320(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsConsolePlatform_ReturnValue_1;          // 0x0328(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_329[0x7];                                      // 0x0329(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class Ubp_SpecialOptionsSave_C*               CallFunc_GetSpecialOptions_SpecialOptions;         // 0x0330(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0338(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_SaveGame_ReturnValue;                     // 0x0339(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_33A[0x6];                                      // 0x033A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class Ubp_SpecialOptionsSave_C*               CallFunc_GetSpecialOptions_SpecialOptions_1;       // 0x0340(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class Ubp_SpecialOptionsSave_C*               CallFunc_GetSpecialOptions_SpecialOptions_2;       // 0x0348(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_SaveGame_ReturnValue_1;                   // 0x0350(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_SaveGame_ReturnValue_2;                   // 0x0351(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_352[0x6];                                      // 0x0352(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class Ubp_SpecialOptionsSave_C*               CallFunc_GetSpecialOptions_SpecialOptions_3;       // 0x0358(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UVivoxLocalPlayer*                      CallFunc_GetLocalPlayerSubsystem_ReturnValue_1;    // 0x0360(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_9;                    // 0x0368(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ECheckBoxState                                K2Node_Select_Default;                             // 0x0369(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_36A[0x6];                                      // 0x036A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Conv_IntToText_ReturnValue;               // 0x0370(0x0018)()
	bool                                          CallFunc_SetOutputGain_ReturnValue_1;              // 0x0388(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_389[0x3];                                      // 0x0389(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_Conv_IntToFloat_ReturnValue_2;            // 0x038C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_IntToText_ReturnValue_1;             // 0x0390(0x0018)()
	bool                                          CallFunc_SetInputVolumeGain_ReturnValue_1;         // 0x03A8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3A9[0x3];                                      // 0x03A9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_Conv_IntToFloat_ReturnValue_3;            // 0x03AC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UVivoxLocalPlayer*                      CallFunc_GetLocalPlayerSubsystem_ReturnValue_2;    // 0x03B0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_10;                   // 0x03B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_GetPushToTalk_ReturnValue;                // 0x03B9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3BA[0x2];                                      // 0x03BA(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(const class FString& OutputDeviceId)> K2Node_CreateDelegate_OutputDelegate_5;            // 0x03BC(0x0010)(ZeroConstructor, NoDestructor)
	uint8                                         Pad_3CC[0x4];                                      // 0x03CC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 K2Node_ComponentBoundEvent_SelectedItem_1;         // 0x03D0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	ESelectInfo                                   K2Node_ComponentBoundEvent_SelectionType_1;        // 0x03E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3E1[0x7];                                      // 0x03E1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 K2Node_ComponentBoundEvent_SelectedItem;           // 0x03E8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	ESelectInfo                                   K2Node_ComponentBoundEvent_SelectionType;          // 0x03F8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x03F9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice) == 0x000008, "Wrong alignment on bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice");
static_assert(sizeof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice) == 0x000400, "Wrong size on bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, EntryPoint) == 0x000000, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::EntryPoint' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, Temp_byte_Variable) == 0x000004, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, K2Node_CreateDelegate_OutputDelegate) == 0x000008, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, K2Node_CreateDelegate_OutputDelegate_1) == 0x000018, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, K2Node_CustomEvent_Active_Output_Id) == 0x000028, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::K2Node_CustomEvent_Active_Output_Id' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, K2Node_CustomEvent_Option) == 0x000038, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::K2Node_CustomEvent_Option' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, CallFunc_GetVivoxSettings_LocalSettings) == 0x000048, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::CallFunc_GetVivoxSettings_LocalSettings' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, K2Node_CustomEvent_InputDeviceId_2) == 0x000050, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::K2Node_CustomEvent_InputDeviceId_2' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, CallFunc_IsValid_ReturnValue) == 0x000060, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, CallFunc_GetVivoxSettings_LocalSettings_1) == 0x000068, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::CallFunc_GetVivoxSettings_LocalSettings_1' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, K2Node_CustomEvent_InputDeviceId_1) == 0x000070, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::K2Node_CustomEvent_InputDeviceId_1' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, CallFunc_GetVivoxSettings_LocalSettings_2) == 0x000080, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::CallFunc_GetVivoxSettings_LocalSettings_2' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, K2Node_CustomEvent_InputDeviceId) == 0x000088, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::K2Node_CustomEvent_InputDeviceId' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, CallFunc_GetVivoxSettings_LocalSettings_3) == 0x000098, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::CallFunc_GetVivoxSettings_LocalSettings_3' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, K2Node_CustomEvent_OutputDeviceId_2) == 0x0000A0, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::K2Node_CustomEvent_OutputDeviceId_2' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, CallFunc_GetVivoxSettings_LocalSettings_4) == 0x0000B0, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::CallFunc_GetVivoxSettings_LocalSettings_4' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, K2Node_CustomEvent_OutputDeviceId_1) == 0x0000B8, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::K2Node_CustomEvent_OutputDeviceId_1' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, CallFunc_GetVivoxSettings_LocalSettings_5) == 0x0000C8, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::CallFunc_GetVivoxSettings_LocalSettings_5' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, K2Node_CustomEvent_OutputDeviceId) == 0x0000D0, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::K2Node_CustomEvent_OutputDeviceId' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, Temp_byte_Variable_1) == 0x0000E0, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::Temp_byte_Variable_1' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, CallFunc_GetVivoxSettings_LocalSettings_6) == 0x0000E8, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::CallFunc_GetVivoxSettings_LocalSettings_6' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, CallFunc_IsValid_ReturnValue_1) == 0x0000F0, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, CallFunc_GetAvailableOutputDevices_DeviceIdToName) == 0x0000F8, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::CallFunc_GetAvailableOutputDevices_DeviceIdToName' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, CallFunc_GetVivoxSettings_LocalSettings_7) == 0x000148, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::CallFunc_GetVivoxSettings_LocalSettings_7' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, CallFunc_IsValid_ReturnValue_2) == 0x000150, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::CallFunc_IsValid_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, CallFunc_GetAvailableInputDevices_DeviceidToName) == 0x000158, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::CallFunc_GetAvailableInputDevices_DeviceidToName' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, CallFunc_GetVivoxSettings_LocalSettings_8) == 0x0001A8, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::CallFunc_GetVivoxSettings_LocalSettings_8' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, CallFunc_IsValid_ReturnValue_3) == 0x0001B0, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::CallFunc_IsValid_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, CallFunc_GetEffectiveOutputDeviceId_ReturnValue) == 0x0001B8, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::CallFunc_GetEffectiveOutputDeviceId_ReturnValue' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, CallFunc_GetVivoxSettings_LocalSettings_9) == 0x0001C8, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::CallFunc_GetVivoxSettings_LocalSettings_9' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, CallFunc_IsValid_ReturnValue_4) == 0x0001D0, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::CallFunc_IsValid_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, K2Node_CreateDelegate_OutputDelegate_2) == 0x0001D4, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::K2Node_CreateDelegate_OutputDelegate_2' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, CallFunc_GetVivoxSettings_LocalSettings_10) == 0x0001E8, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::CallFunc_GetVivoxSettings_LocalSettings_10' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, CallFunc_GetVivoxSettings_LocalSettings_11) == 0x0001F0, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::CallFunc_GetVivoxSettings_LocalSettings_11' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, CallFunc_GetEffectiveInputDeviceId_ReturnValue) == 0x0001F8, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::CallFunc_GetEffectiveInputDeviceId_ReturnValue' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, CallFunc_GetEffectiveInputDeviceId_ReturnValue_1) == 0x000208, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::CallFunc_GetEffectiveInputDeviceId_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, CallFunc_GetVivoxSettings_LocalSettings_12) == 0x000218, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::CallFunc_GetVivoxSettings_LocalSettings_12' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, CallFunc_GetVivoxSettings_LocalSettings_13) == 0x000220, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::CallFunc_GetVivoxSettings_LocalSettings_13' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, CallFunc_GetEffectiveOutputDeviceId_ReturnValue_1) == 0x000228, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::CallFunc_GetEffectiveOutputDeviceId_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, CallFunc_GetEffectiveOutputDeviceId_ReturnValue_2) == 0x000238, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::CallFunc_GetEffectiveOutputDeviceId_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, CallFunc_GetVivoxSettings_LocalSettings_14) == 0x000248, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::CallFunc_GetVivoxSettings_LocalSettings_14' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, CallFunc_GetVivoxSettings_LocalSettings_15) == 0x000250, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::CallFunc_GetVivoxSettings_LocalSettings_15' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, CallFunc_IsValid_ReturnValue_5) == 0x000258, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::CallFunc_IsValid_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, CallFunc_GetEffectiveOutputDeviceId_ReturnValue_3) == 0x000260, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::CallFunc_GetEffectiveOutputDeviceId_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, CallFunc_GetEffectiveInputDeviceId_ReturnValue_2) == 0x000270, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::CallFunc_GetEffectiveInputDeviceId_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, CallFunc_GetVivoxSettings_LocalSettings_16) == 0x000280, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::CallFunc_GetVivoxSettings_LocalSettings_16' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, CallFunc_GetOutputGain_ReturnValue) == 0x000288, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::CallFunc_GetOutputGain_ReturnValue' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, CallFunc_GetVivoxSettings_LocalSettings_17) == 0x000290, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::CallFunc_GetVivoxSettings_LocalSettings_17' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, CallFunc_Conv_IntToFloat_ReturnValue) == 0x000298, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::CallFunc_Conv_IntToFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, Temp_bool_Variable) == 0x00029C, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, K2Node_CreateDelegate_OutputDelegate_3) == 0x0002A0, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::K2Node_CreateDelegate_OutputDelegate_3' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, K2Node_ComponentBoundEvent_IsChecked) == 0x0002B0, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::K2Node_ComponentBoundEvent_IsChecked' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, CallFunc_GetVivoxSettings_LocalSettings_18) == 0x0002B8, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::CallFunc_GetVivoxSettings_LocalSettings_18' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, CallFunc_GetVivoxSettings_LocalSettings_19) == 0x0002C0, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::CallFunc_GetVivoxSettings_LocalSettings_19' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, CallFunc_IsValid_ReturnValue_6) == 0x0002C8, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::CallFunc_IsValid_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, CallFunc_GetInputVolumeGain_ReturnValue) == 0x0002CC, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::CallFunc_GetInputVolumeGain_ReturnValue' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, CallFunc_Conv_IntToFloat_ReturnValue_1) == 0x0002D0, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::CallFunc_Conv_IntToFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, CallFunc_GetValue_ReturnValue) == 0x0002D4, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::CallFunc_GetValue_ReturnValue' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, CallFunc_FTrunc_ReturnValue) == 0x0002D8, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::CallFunc_FTrunc_ReturnValue' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, CallFunc_SetInputVolumeGain_ReturnValue) == 0x0002DC, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::CallFunc_SetInputVolumeGain_ReturnValue' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, CallFunc_GetValue_ReturnValue_1) == 0x0002E0, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::CallFunc_GetValue_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, CallFunc_FTrunc_ReturnValue_1) == 0x0002E4, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::CallFunc_FTrunc_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, CallFunc_IsConsolePlatform_ReturnValue) == 0x0002E8, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::CallFunc_IsConsolePlatform_ReturnValue' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, CallFunc_SetOutputGain_ReturnValue) == 0x0002E9, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::CallFunc_SetOutputGain_ReturnValue' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, CallFunc_GetLocalPlayerSubsystem_ReturnValue) == 0x0002F0, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::CallFunc_GetLocalPlayerSubsystem_ReturnValue' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, CallFunc_IsValid_ReturnValue_7) == 0x0002F8, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::CallFunc_IsValid_ReturnValue_7' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, K2Node_CreateDelegate_OutputDelegate_4) == 0x0002FC, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::K2Node_CreateDelegate_OutputDelegate_4' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, CallFunc_GetVivoxSettings_LocalSettings_20) == 0x000310, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::CallFunc_GetVivoxSettings_LocalSettings_20' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, CallFunc_IsValid_ReturnValue_8) == 0x000318, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::CallFunc_IsValid_ReturnValue_8' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, CallFunc_GetVivoxSettings_LocalSettings_21) == 0x000320, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::CallFunc_GetVivoxSettings_LocalSettings_21' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, CallFunc_IsConsolePlatform_ReturnValue_1) == 0x000328, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::CallFunc_IsConsolePlatform_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, CallFunc_GetSpecialOptions_SpecialOptions) == 0x000330, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::CallFunc_GetSpecialOptions_SpecialOptions' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, CallFunc_Not_PreBool_ReturnValue) == 0x000338, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, CallFunc_SaveGame_ReturnValue) == 0x000339, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::CallFunc_SaveGame_ReturnValue' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, CallFunc_GetSpecialOptions_SpecialOptions_1) == 0x000340, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::CallFunc_GetSpecialOptions_SpecialOptions_1' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, CallFunc_GetSpecialOptions_SpecialOptions_2) == 0x000348, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::CallFunc_GetSpecialOptions_SpecialOptions_2' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, CallFunc_SaveGame_ReturnValue_1) == 0x000350, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::CallFunc_SaveGame_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, CallFunc_SaveGame_ReturnValue_2) == 0x000351, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::CallFunc_SaveGame_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, CallFunc_GetSpecialOptions_SpecialOptions_3) == 0x000358, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::CallFunc_GetSpecialOptions_SpecialOptions_3' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, CallFunc_GetLocalPlayerSubsystem_ReturnValue_1) == 0x000360, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::CallFunc_GetLocalPlayerSubsystem_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, CallFunc_IsValid_ReturnValue_9) == 0x000368, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::CallFunc_IsValid_ReturnValue_9' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, K2Node_Select_Default) == 0x000369, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, CallFunc_Conv_IntToText_ReturnValue) == 0x000370, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::CallFunc_Conv_IntToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, CallFunc_SetOutputGain_ReturnValue_1) == 0x000388, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::CallFunc_SetOutputGain_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, CallFunc_Conv_IntToFloat_ReturnValue_2) == 0x00038C, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::CallFunc_Conv_IntToFloat_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, CallFunc_Conv_IntToText_ReturnValue_1) == 0x000390, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::CallFunc_Conv_IntToText_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, CallFunc_SetInputVolumeGain_ReturnValue_1) == 0x0003A8, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::CallFunc_SetInputVolumeGain_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, CallFunc_Conv_IntToFloat_ReturnValue_3) == 0x0003AC, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::CallFunc_Conv_IntToFloat_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, CallFunc_GetLocalPlayerSubsystem_ReturnValue_2) == 0x0003B0, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::CallFunc_GetLocalPlayerSubsystem_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, CallFunc_IsValid_ReturnValue_10) == 0x0003B8, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::CallFunc_IsValid_ReturnValue_10' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, CallFunc_GetPushToTalk_ReturnValue) == 0x0003B9, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::CallFunc_GetPushToTalk_ReturnValue' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, K2Node_CreateDelegate_OutputDelegate_5) == 0x0003BC, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::K2Node_CreateDelegate_OutputDelegate_5' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, K2Node_ComponentBoundEvent_SelectedItem_1) == 0x0003D0, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::K2Node_ComponentBoundEvent_SelectedItem_1' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, K2Node_ComponentBoundEvent_SelectionType_1) == 0x0003E0, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::K2Node_ComponentBoundEvent_SelectionType_1' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, K2Node_ComponentBoundEvent_SelectedItem) == 0x0003E8, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::K2Node_ComponentBoundEvent_SelectedItem' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, K2Node_ComponentBoundEvent_SelectionType) == 0x0003F8, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::K2Node_ComponentBoundEvent_SelectionType' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice, K2Node_Event_IsDesignTime) == 0x0003F9, "Member 'bp_wi_OptionsVoice_C_ExecuteUbergraph_bp_wi_OptionsVoice::K2Node_Event_IsDesignTime' has a wrong offset!");

// Function bp_wi_OptionsVoice.bp_wi_OptionsVoice_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct bp_wi_OptionsVoice_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(bp_wi_OptionsVoice_C_PreConstruct) == 0x000001, "Wrong alignment on bp_wi_OptionsVoice_C_PreConstruct");
static_assert(sizeof(bp_wi_OptionsVoice_C_PreConstruct) == 0x000001, "Wrong size on bp_wi_OptionsVoice_C_PreConstruct");
static_assert(offsetof(bp_wi_OptionsVoice_C_PreConstruct, IsDesignTime) == 0x000000, "Member 'bp_wi_OptionsVoice_C_PreConstruct::IsDesignTime' has a wrong offset!");

// Function bp_wi_OptionsVoice.bp_wi_OptionsVoice_C.BndEvt__bp_wi_OptionsVoice_Microphone_1_K2Node_ComponentBoundEvent_7_OnSelectionChanged__DelegateSignature
// 0x0018 (0x0018 - 0x0000)
struct bp_wi_OptionsVoice_C_BndEvt__bp_wi_OptionsVoice_Microphone_1_K2Node_ComponentBoundEvent_7_OnSelectionChanged__DelegateSignature final
{
public:
	class FString                                 SelectedItem;                                      // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
	ESelectInfo                                   SelectionType;                                     // 0x0010(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(bp_wi_OptionsVoice_C_BndEvt__bp_wi_OptionsVoice_Microphone_1_K2Node_ComponentBoundEvent_7_OnSelectionChanged__DelegateSignature) == 0x000008, "Wrong alignment on bp_wi_OptionsVoice_C_BndEvt__bp_wi_OptionsVoice_Microphone_1_K2Node_ComponentBoundEvent_7_OnSelectionChanged__DelegateSignature");
static_assert(sizeof(bp_wi_OptionsVoice_C_BndEvt__bp_wi_OptionsVoice_Microphone_1_K2Node_ComponentBoundEvent_7_OnSelectionChanged__DelegateSignature) == 0x000018, "Wrong size on bp_wi_OptionsVoice_C_BndEvt__bp_wi_OptionsVoice_Microphone_1_K2Node_ComponentBoundEvent_7_OnSelectionChanged__DelegateSignature");
static_assert(offsetof(bp_wi_OptionsVoice_C_BndEvt__bp_wi_OptionsVoice_Microphone_1_K2Node_ComponentBoundEvent_7_OnSelectionChanged__DelegateSignature, SelectedItem) == 0x000000, "Member 'bp_wi_OptionsVoice_C_BndEvt__bp_wi_OptionsVoice_Microphone_1_K2Node_ComponentBoundEvent_7_OnSelectionChanged__DelegateSignature::SelectedItem' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_BndEvt__bp_wi_OptionsVoice_Microphone_1_K2Node_ComponentBoundEvent_7_OnSelectionChanged__DelegateSignature, SelectionType) == 0x000010, "Member 'bp_wi_OptionsVoice_C_BndEvt__bp_wi_OptionsVoice_Microphone_1_K2Node_ComponentBoundEvent_7_OnSelectionChanged__DelegateSignature::SelectionType' has a wrong offset!");

// Function bp_wi_OptionsVoice.bp_wi_OptionsVoice_C.BndEvt__bp_wi_OptionsVoice_Speaker_K2Node_ComponentBoundEvent_5_OnSelectionChanged__DelegateSignature
// 0x0018 (0x0018 - 0x0000)
struct bp_wi_OptionsVoice_C_BndEvt__bp_wi_OptionsVoice_Speaker_K2Node_ComponentBoundEvent_5_OnSelectionChanged__DelegateSignature final
{
public:
	class FString                                 SelectedItem;                                      // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
	ESelectInfo                                   SelectionType;                                     // 0x0010(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(bp_wi_OptionsVoice_C_BndEvt__bp_wi_OptionsVoice_Speaker_K2Node_ComponentBoundEvent_5_OnSelectionChanged__DelegateSignature) == 0x000008, "Wrong alignment on bp_wi_OptionsVoice_C_BndEvt__bp_wi_OptionsVoice_Speaker_K2Node_ComponentBoundEvent_5_OnSelectionChanged__DelegateSignature");
static_assert(sizeof(bp_wi_OptionsVoice_C_BndEvt__bp_wi_OptionsVoice_Speaker_K2Node_ComponentBoundEvent_5_OnSelectionChanged__DelegateSignature) == 0x000018, "Wrong size on bp_wi_OptionsVoice_C_BndEvt__bp_wi_OptionsVoice_Speaker_K2Node_ComponentBoundEvent_5_OnSelectionChanged__DelegateSignature");
static_assert(offsetof(bp_wi_OptionsVoice_C_BndEvt__bp_wi_OptionsVoice_Speaker_K2Node_ComponentBoundEvent_5_OnSelectionChanged__DelegateSignature, SelectedItem) == 0x000000, "Member 'bp_wi_OptionsVoice_C_BndEvt__bp_wi_OptionsVoice_Speaker_K2Node_ComponentBoundEvent_5_OnSelectionChanged__DelegateSignature::SelectedItem' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_BndEvt__bp_wi_OptionsVoice_Speaker_K2Node_ComponentBoundEvent_5_OnSelectionChanged__DelegateSignature, SelectionType) == 0x000010, "Member 'bp_wi_OptionsVoice_C_BndEvt__bp_wi_OptionsVoice_Speaker_K2Node_ComponentBoundEvent_5_OnSelectionChanged__DelegateSignature::SelectionType' has a wrong offset!");

// Function bp_wi_OptionsVoice.bp_wi_OptionsVoice_C.BndEvt__SetUsePushToTalk_K2Node_ComponentBoundEvent_2_OnCheckStateChanged__DelegateSignature
// 0x0001 (0x0001 - 0x0000)
struct bp_wi_OptionsVoice_C_BndEvt__SetUsePushToTalk_K2Node_ComponentBoundEvent_2_OnCheckStateChanged__DelegateSignature final
{
public:
	bool                                          IsChecked;                                         // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(bp_wi_OptionsVoice_C_BndEvt__SetUsePushToTalk_K2Node_ComponentBoundEvent_2_OnCheckStateChanged__DelegateSignature) == 0x000001, "Wrong alignment on bp_wi_OptionsVoice_C_BndEvt__SetUsePushToTalk_K2Node_ComponentBoundEvent_2_OnCheckStateChanged__DelegateSignature");
static_assert(sizeof(bp_wi_OptionsVoice_C_BndEvt__SetUsePushToTalk_K2Node_ComponentBoundEvent_2_OnCheckStateChanged__DelegateSignature) == 0x000001, "Wrong size on bp_wi_OptionsVoice_C_BndEvt__SetUsePushToTalk_K2Node_ComponentBoundEvent_2_OnCheckStateChanged__DelegateSignature");
static_assert(offsetof(bp_wi_OptionsVoice_C_BndEvt__SetUsePushToTalk_K2Node_ComponentBoundEvent_2_OnCheckStateChanged__DelegateSignature, IsChecked) == 0x000000, "Member 'bp_wi_OptionsVoice_C_BndEvt__SetUsePushToTalk_K2Node_ComponentBoundEvent_2_OnCheckStateChanged__DelegateSignature::IsChecked' has a wrong offset!");

// Function bp_wi_OptionsVoice.bp_wi_OptionsVoice_C.HandleOutputDeviceChanged
// 0x0010 (0x0010 - 0x0000)
struct bp_wi_OptionsVoice_C_HandleOutputDeviceChanged final
{
public:
	class FString                                 OutputDeviceId;                                    // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
};
static_assert(alignof(bp_wi_OptionsVoice_C_HandleOutputDeviceChanged) == 0x000008, "Wrong alignment on bp_wi_OptionsVoice_C_HandleOutputDeviceChanged");
static_assert(sizeof(bp_wi_OptionsVoice_C_HandleOutputDeviceChanged) == 0x000010, "Wrong size on bp_wi_OptionsVoice_C_HandleOutputDeviceChanged");
static_assert(offsetof(bp_wi_OptionsVoice_C_HandleOutputDeviceChanged, OutputDeviceId) == 0x000000, "Member 'bp_wi_OptionsVoice_C_HandleOutputDeviceChanged::OutputDeviceId' has a wrong offset!");

// Function bp_wi_OptionsVoice.bp_wi_OptionsVoice_C.HandleOutputDeviceRemoved
// 0x0010 (0x0010 - 0x0000)
struct bp_wi_OptionsVoice_C_HandleOutputDeviceRemoved final
{
public:
	class FString                                 OutputDeviceId;                                    // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
};
static_assert(alignof(bp_wi_OptionsVoice_C_HandleOutputDeviceRemoved) == 0x000008, "Wrong alignment on bp_wi_OptionsVoice_C_HandleOutputDeviceRemoved");
static_assert(sizeof(bp_wi_OptionsVoice_C_HandleOutputDeviceRemoved) == 0x000010, "Wrong size on bp_wi_OptionsVoice_C_HandleOutputDeviceRemoved");
static_assert(offsetof(bp_wi_OptionsVoice_C_HandleOutputDeviceRemoved, OutputDeviceId) == 0x000000, "Member 'bp_wi_OptionsVoice_C_HandleOutputDeviceRemoved::OutputDeviceId' has a wrong offset!");

// Function bp_wi_OptionsVoice.bp_wi_OptionsVoice_C.HandleOutputDeviceAdded
// 0x0010 (0x0010 - 0x0000)
struct bp_wi_OptionsVoice_C_HandleOutputDeviceAdded final
{
public:
	class FString                                 OutputDeviceId;                                    // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
};
static_assert(alignof(bp_wi_OptionsVoice_C_HandleOutputDeviceAdded) == 0x000008, "Wrong alignment on bp_wi_OptionsVoice_C_HandleOutputDeviceAdded");
static_assert(sizeof(bp_wi_OptionsVoice_C_HandleOutputDeviceAdded) == 0x000010, "Wrong size on bp_wi_OptionsVoice_C_HandleOutputDeviceAdded");
static_assert(offsetof(bp_wi_OptionsVoice_C_HandleOutputDeviceAdded, OutputDeviceId) == 0x000000, "Member 'bp_wi_OptionsVoice_C_HandleOutputDeviceAdded::OutputDeviceId' has a wrong offset!");

// Function bp_wi_OptionsVoice.bp_wi_OptionsVoice_C.HandleInputDeviceChanged
// 0x0010 (0x0010 - 0x0000)
struct bp_wi_OptionsVoice_C_HandleInputDeviceChanged final
{
public:
	class FString                                 InputDeviceId;                                     // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
};
static_assert(alignof(bp_wi_OptionsVoice_C_HandleInputDeviceChanged) == 0x000008, "Wrong alignment on bp_wi_OptionsVoice_C_HandleInputDeviceChanged");
static_assert(sizeof(bp_wi_OptionsVoice_C_HandleInputDeviceChanged) == 0x000010, "Wrong size on bp_wi_OptionsVoice_C_HandleInputDeviceChanged");
static_assert(offsetof(bp_wi_OptionsVoice_C_HandleInputDeviceChanged, InputDeviceId) == 0x000000, "Member 'bp_wi_OptionsVoice_C_HandleInputDeviceChanged::InputDeviceId' has a wrong offset!");

// Function bp_wi_OptionsVoice.bp_wi_OptionsVoice_C.HandleInputDeviceRemoved
// 0x0010 (0x0010 - 0x0000)
struct bp_wi_OptionsVoice_C_HandleInputDeviceRemoved final
{
public:
	class FString                                 InputDeviceId;                                     // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
};
static_assert(alignof(bp_wi_OptionsVoice_C_HandleInputDeviceRemoved) == 0x000008, "Wrong alignment on bp_wi_OptionsVoice_C_HandleInputDeviceRemoved");
static_assert(sizeof(bp_wi_OptionsVoice_C_HandleInputDeviceRemoved) == 0x000010, "Wrong size on bp_wi_OptionsVoice_C_HandleInputDeviceRemoved");
static_assert(offsetof(bp_wi_OptionsVoice_C_HandleInputDeviceRemoved, InputDeviceId) == 0x000000, "Member 'bp_wi_OptionsVoice_C_HandleInputDeviceRemoved::InputDeviceId' has a wrong offset!");

// Function bp_wi_OptionsVoice.bp_wi_OptionsVoice_C.HandleInputDeviceAdded
// 0x0010 (0x0010 - 0x0000)
struct bp_wi_OptionsVoice_C_HandleInputDeviceAdded final
{
public:
	class FString                                 InputDeviceId;                                     // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
};
static_assert(alignof(bp_wi_OptionsVoice_C_HandleInputDeviceAdded) == 0x000008, "Wrong alignment on bp_wi_OptionsVoice_C_HandleInputDeviceAdded");
static_assert(sizeof(bp_wi_OptionsVoice_C_HandleInputDeviceAdded) == 0x000010, "Wrong size on bp_wi_OptionsVoice_C_HandleInputDeviceAdded");
static_assert(offsetof(bp_wi_OptionsVoice_C_HandleInputDeviceAdded, InputDeviceId) == 0x000000, "Member 'bp_wi_OptionsVoice_C_HandleInputDeviceAdded::InputDeviceId' has a wrong offset!");

// Function bp_wi_OptionsVoice.bp_wi_OptionsVoice_C.SetVivoxSelectedInputDevice
// 0x0010 (0x0010 - 0x0000)
struct bp_wi_OptionsVoice_C_SetVivoxSelectedInputDevice final
{
public:
	class FString                                 Option;                                            // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
};
static_assert(alignof(bp_wi_OptionsVoice_C_SetVivoxSelectedInputDevice) == 0x000008, "Wrong alignment on bp_wi_OptionsVoice_C_SetVivoxSelectedInputDevice");
static_assert(sizeof(bp_wi_OptionsVoice_C_SetVivoxSelectedInputDevice) == 0x000010, "Wrong size on bp_wi_OptionsVoice_C_SetVivoxSelectedInputDevice");
static_assert(offsetof(bp_wi_OptionsVoice_C_SetVivoxSelectedInputDevice, Option) == 0x000000, "Member 'bp_wi_OptionsVoice_C_SetVivoxSelectedInputDevice::Option' has a wrong offset!");

// Function bp_wi_OptionsVoice.bp_wi_OptionsVoice_C.SetVivoxSelectedOutputDevice
// 0x0010 (0x0010 - 0x0000)
struct bp_wi_OptionsVoice_C_SetVivoxSelectedOutputDevice final
{
public:
	class FString                                 Active_Output_Id;                                  // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
};
static_assert(alignof(bp_wi_OptionsVoice_C_SetVivoxSelectedOutputDevice) == 0x000008, "Wrong alignment on bp_wi_OptionsVoice_C_SetVivoxSelectedOutputDevice");
static_assert(sizeof(bp_wi_OptionsVoice_C_SetVivoxSelectedOutputDevice) == 0x000010, "Wrong size on bp_wi_OptionsVoice_C_SetVivoxSelectedOutputDevice");
static_assert(offsetof(bp_wi_OptionsVoice_C_SetVivoxSelectedOutputDevice, Active_Output_Id) == 0x000000, "Member 'bp_wi_OptionsVoice_C_SetVivoxSelectedOutputDevice::Active_Output_Id' has a wrong offset!");

// Function bp_wi_OptionsVoice.bp_wi_OptionsVoice_C.Set Combo Box Device Options
// 0x0128 (0x0128 - 0x0000)
struct bp_wi_OptionsVoice_C_Set_Combo_Box_Device_Options final
{
public:
	class UComboBoxString*                        ComboBox;                                          // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 Effective_Device_Id;                               // 0x0008(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
	TMap<class FString, class FString>            AvailableDevicesIdToName;                          // 0x0018(0x0050)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	TMap<int32, class FString>                    Out_AvailableDeviceIndexToDeviceId;                // 0x0068(0x0050)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	TArray<class FString>                         Local_Device_Names;                                // 0x00B8(0x0010)(Edit, BlueprintVisible)
	TArray<class FString>                         Local_Device_Ids;                                  // 0x00C8(0x0010)(Edit, BlueprintVisible)
	TArray<class FString>                         CallFunc_Map_Values_Values;                        // 0x00D8(0x0010)(ReferenceParm)
	TArray<class FString>                         CallFunc_Map_Keys_Keys;                            // 0x00E8(0x0010)(ReferenceParm)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x00F8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_FC[0x4];                                       // 0x00FC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Array_Get_Item;                           // 0x0100(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_StrStr_ReturnValue;            // 0x0110(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_111[0x3];                                      // 0x0111(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0114(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0118(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x011C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_11D[0x3];                                      // 0x011D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0120(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(bp_wi_OptionsVoice_C_Set_Combo_Box_Device_Options) == 0x000008, "Wrong alignment on bp_wi_OptionsVoice_C_Set_Combo_Box_Device_Options");
static_assert(sizeof(bp_wi_OptionsVoice_C_Set_Combo_Box_Device_Options) == 0x000128, "Wrong size on bp_wi_OptionsVoice_C_Set_Combo_Box_Device_Options");
static_assert(offsetof(bp_wi_OptionsVoice_C_Set_Combo_Box_Device_Options, ComboBox) == 0x000000, "Member 'bp_wi_OptionsVoice_C_Set_Combo_Box_Device_Options::ComboBox' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_Set_Combo_Box_Device_Options, Effective_Device_Id) == 0x000008, "Member 'bp_wi_OptionsVoice_C_Set_Combo_Box_Device_Options::Effective_Device_Id' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_Set_Combo_Box_Device_Options, AvailableDevicesIdToName) == 0x000018, "Member 'bp_wi_OptionsVoice_C_Set_Combo_Box_Device_Options::AvailableDevicesIdToName' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_Set_Combo_Box_Device_Options, Out_AvailableDeviceIndexToDeviceId) == 0x000068, "Member 'bp_wi_OptionsVoice_C_Set_Combo_Box_Device_Options::Out_AvailableDeviceIndexToDeviceId' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_Set_Combo_Box_Device_Options, Local_Device_Names) == 0x0000B8, "Member 'bp_wi_OptionsVoice_C_Set_Combo_Box_Device_Options::Local_Device_Names' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_Set_Combo_Box_Device_Options, Local_Device_Ids) == 0x0000C8, "Member 'bp_wi_OptionsVoice_C_Set_Combo_Box_Device_Options::Local_Device_Ids' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_Set_Combo_Box_Device_Options, CallFunc_Map_Values_Values) == 0x0000D8, "Member 'bp_wi_OptionsVoice_C_Set_Combo_Box_Device_Options::CallFunc_Map_Values_Values' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_Set_Combo_Box_Device_Options, CallFunc_Map_Keys_Keys) == 0x0000E8, "Member 'bp_wi_OptionsVoice_C_Set_Combo_Box_Device_Options::CallFunc_Map_Keys_Keys' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_Set_Combo_Box_Device_Options, Temp_int_Array_Index_Variable) == 0x0000F8, "Member 'bp_wi_OptionsVoice_C_Set_Combo_Box_Device_Options::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_Set_Combo_Box_Device_Options, CallFunc_Array_Get_Item) == 0x000100, "Member 'bp_wi_OptionsVoice_C_Set_Combo_Box_Device_Options::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_Set_Combo_Box_Device_Options, CallFunc_EqualEqual_StrStr_ReturnValue) == 0x000110, "Member 'bp_wi_OptionsVoice_C_Set_Combo_Box_Device_Options::CallFunc_EqualEqual_StrStr_ReturnValue' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_Set_Combo_Box_Device_Options, CallFunc_Array_Length_ReturnValue) == 0x000114, "Member 'bp_wi_OptionsVoice_C_Set_Combo_Box_Device_Options::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_Set_Combo_Box_Device_Options, Temp_int_Loop_Counter_Variable) == 0x000118, "Member 'bp_wi_OptionsVoice_C_Set_Combo_Box_Device_Options::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_Set_Combo_Box_Device_Options, CallFunc_Less_IntInt_ReturnValue) == 0x00011C, "Member 'bp_wi_OptionsVoice_C_Set_Combo_Box_Device_Options::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_Set_Combo_Box_Device_Options, CallFunc_Add_IntInt_ReturnValue) == 0x000120, "Member 'bp_wi_OptionsVoice_C_Set_Combo_Box_Device_Options::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");

// Function bp_wi_OptionsVoice.bp_wi_OptionsVoice_C.Apply Selection
// 0x0088 (0x0088 - 0x0000)
struct bp_wi_OptionsVoice_C_Apply_Selection final
{
public:
	bool                                          IsInputDevice;                                     // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	ESelectInfo                                   Selection_Type;                                    // 0x0001(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2[0x6];                                        // 0x0002(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TMap<int32, class FString>                    Available_Device_IndexToId;                        // 0x0008(0x0050)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	class UComboBoxString*                        ComboBox;                                          // 0x0058(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ULocalSettings*                         CallFunc_GetVivoxSettings_LocalSettings;           // 0x0060(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetSelectedIndex_ReturnValue;             // 0x0068(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x006C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_6D[0x3];                                       // 0x006D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Map_Find_Value;                           // 0x0070(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_Map_Find_ReturnValue;                     // 0x0080(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_SetOutputDevice_ReturnValue;              // 0x0081(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_SetInputDevice_ReturnValue;               // 0x0082(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(bp_wi_OptionsVoice_C_Apply_Selection) == 0x000008, "Wrong alignment on bp_wi_OptionsVoice_C_Apply_Selection");
static_assert(sizeof(bp_wi_OptionsVoice_C_Apply_Selection) == 0x000088, "Wrong size on bp_wi_OptionsVoice_C_Apply_Selection");
static_assert(offsetof(bp_wi_OptionsVoice_C_Apply_Selection, IsInputDevice) == 0x000000, "Member 'bp_wi_OptionsVoice_C_Apply_Selection::IsInputDevice' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_Apply_Selection, Selection_Type) == 0x000001, "Member 'bp_wi_OptionsVoice_C_Apply_Selection::Selection_Type' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_Apply_Selection, Available_Device_IndexToId) == 0x000008, "Member 'bp_wi_OptionsVoice_C_Apply_Selection::Available_Device_IndexToId' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_Apply_Selection, ComboBox) == 0x000058, "Member 'bp_wi_OptionsVoice_C_Apply_Selection::ComboBox' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_Apply_Selection, CallFunc_GetVivoxSettings_LocalSettings) == 0x000060, "Member 'bp_wi_OptionsVoice_C_Apply_Selection::CallFunc_GetVivoxSettings_LocalSettings' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_Apply_Selection, CallFunc_GetSelectedIndex_ReturnValue) == 0x000068, "Member 'bp_wi_OptionsVoice_C_Apply_Selection::CallFunc_GetSelectedIndex_ReturnValue' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_Apply_Selection, K2Node_SwitchEnum_CmpSuccess) == 0x00006C, "Member 'bp_wi_OptionsVoice_C_Apply_Selection::K2Node_SwitchEnum_CmpSuccess' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_Apply_Selection, CallFunc_Map_Find_Value) == 0x000070, "Member 'bp_wi_OptionsVoice_C_Apply_Selection::CallFunc_Map_Find_Value' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_Apply_Selection, CallFunc_Map_Find_ReturnValue) == 0x000080, "Member 'bp_wi_OptionsVoice_C_Apply_Selection::CallFunc_Map_Find_ReturnValue' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_Apply_Selection, CallFunc_SetOutputDevice_ReturnValue) == 0x000081, "Member 'bp_wi_OptionsVoice_C_Apply_Selection::CallFunc_SetOutputDevice_ReturnValue' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_Apply_Selection, CallFunc_SetInputDevice_ReturnValue) == 0x000082, "Member 'bp_wi_OptionsVoice_C_Apply_Selection::CallFunc_SetInputDevice_ReturnValue' has a wrong offset!");

// Function bp_wi_OptionsVoice.bp_wi_OptionsVoice_C.GetSpecialOptions
// 0x0028 (0x0028 - 0x0000)
struct bp_wi_OptionsVoice_C_GetSpecialOptions final
{
public:
	class Ubp_SpecialOptionsSave_C*               SpecialOptions;                                    // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class Ubp_SpecialOptionsSave_C*               CallFunc_CreateSaveGameObject_ReturnValue;         // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USaveGame*                              CallFunc_LoadGame_ReturnValue;                     // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class Ubp_SpecialOptionsSave_C*               K2Node_DynamicCast_AsBp_Special_Options_Save;      // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(bp_wi_OptionsVoice_C_GetSpecialOptions) == 0x000008, "Wrong alignment on bp_wi_OptionsVoice_C_GetSpecialOptions");
static_assert(sizeof(bp_wi_OptionsVoice_C_GetSpecialOptions) == 0x000028, "Wrong size on bp_wi_OptionsVoice_C_GetSpecialOptions");
static_assert(offsetof(bp_wi_OptionsVoice_C_GetSpecialOptions, SpecialOptions) == 0x000000, "Member 'bp_wi_OptionsVoice_C_GetSpecialOptions::SpecialOptions' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_GetSpecialOptions, CallFunc_CreateSaveGameObject_ReturnValue) == 0x000008, "Member 'bp_wi_OptionsVoice_C_GetSpecialOptions::CallFunc_CreateSaveGameObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_GetSpecialOptions, CallFunc_LoadGame_ReturnValue) == 0x000010, "Member 'bp_wi_OptionsVoice_C_GetSpecialOptions::CallFunc_LoadGame_ReturnValue' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_GetSpecialOptions, K2Node_DynamicCast_AsBp_Special_Options_Save) == 0x000018, "Member 'bp_wi_OptionsVoice_C_GetSpecialOptions::K2Node_DynamicCast_AsBp_Special_Options_Save' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_GetSpecialOptions, K2Node_DynamicCast_bSuccess) == 0x000020, "Member 'bp_wi_OptionsVoice_C_GetSpecialOptions::K2Node_DynamicCast_bSuccess' has a wrong offset!");

// Function bp_wi_OptionsVoice.bp_wi_OptionsVoice_C.GetVivoxSettings
// 0x0018 (0x0018 - 0x0000)
struct bp_wi_OptionsVoice_C_GetVivoxSettings final
{
public:
	class ULocalSettings*                         LocalSettings;                                     // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UVivoxLocalPlayer*                      CallFunc_GetLocalPlayerSubsystem_ReturnValue;      // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0011(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(bp_wi_OptionsVoice_C_GetVivoxSettings) == 0x000008, "Wrong alignment on bp_wi_OptionsVoice_C_GetVivoxSettings");
static_assert(sizeof(bp_wi_OptionsVoice_C_GetVivoxSettings) == 0x000018, "Wrong size on bp_wi_OptionsVoice_C_GetVivoxSettings");
static_assert(offsetof(bp_wi_OptionsVoice_C_GetVivoxSettings, LocalSettings) == 0x000000, "Member 'bp_wi_OptionsVoice_C_GetVivoxSettings::LocalSettings' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_GetVivoxSettings, CallFunc_GetLocalPlayerSubsystem_ReturnValue) == 0x000008, "Member 'bp_wi_OptionsVoice_C_GetVivoxSettings::CallFunc_GetLocalPlayerSubsystem_ReturnValue' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_GetVivoxSettings, CallFunc_IsValid_ReturnValue) == 0x000010, "Member 'bp_wi_OptionsVoice_C_GetVivoxSettings::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_GetVivoxSettings, CallFunc_IsValid_ReturnValue_1) == 0x000011, "Member 'bp_wi_OptionsVoice_C_GetVivoxSettings::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");

// Function bp_wi_OptionsVoice.bp_wi_OptionsVoice_C.Get ActiveVivoxPlaybackDeviceOption
// 0x0068 (0x0068 - 0x0000)
struct bp_wi_OptionsVoice_C_Get_ActiveVivoxPlaybackDeviceOption final
{
public:
	class FString                                 Output_Id;                                         // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
	bool                                          Found_Existing;                                    // 0x0010(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_11[0x3];                                       // 0x0011(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Active_Output_Option_Index;                        // 0x0014(0x0004)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_24[0x4];                                       // 0x0024(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class FString>                         CallFunc_Map_Values_Values;                        // 0x0028(0x0010)(ReferenceParm)
	TArray<int32>                                 CallFunc_Map_Keys_Keys;                            // 0x0038(0x0010)(ReferenceParm)
	class FString                                 CallFunc_Array_Get_Item;                           // 0x0048(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_StrStr_ReturnValue;            // 0x0058(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_59[0x3];                                       // 0x0059(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x005C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0060(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(bp_wi_OptionsVoice_C_Get_ActiveVivoxPlaybackDeviceOption) == 0x000008, "Wrong alignment on bp_wi_OptionsVoice_C_Get_ActiveVivoxPlaybackDeviceOption");
static_assert(sizeof(bp_wi_OptionsVoice_C_Get_ActiveVivoxPlaybackDeviceOption) == 0x000068, "Wrong size on bp_wi_OptionsVoice_C_Get_ActiveVivoxPlaybackDeviceOption");
static_assert(offsetof(bp_wi_OptionsVoice_C_Get_ActiveVivoxPlaybackDeviceOption, Output_Id) == 0x000000, "Member 'bp_wi_OptionsVoice_C_Get_ActiveVivoxPlaybackDeviceOption::Output_Id' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_Get_ActiveVivoxPlaybackDeviceOption, Found_Existing) == 0x000010, "Member 'bp_wi_OptionsVoice_C_Get_ActiveVivoxPlaybackDeviceOption::Found_Existing' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_Get_ActiveVivoxPlaybackDeviceOption, Active_Output_Option_Index) == 0x000014, "Member 'bp_wi_OptionsVoice_C_Get_ActiveVivoxPlaybackDeviceOption::Active_Output_Option_Index' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_Get_ActiveVivoxPlaybackDeviceOption, Temp_int_Array_Index_Variable) == 0x000018, "Member 'bp_wi_OptionsVoice_C_Get_ActiveVivoxPlaybackDeviceOption::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_Get_ActiveVivoxPlaybackDeviceOption, Temp_int_Loop_Counter_Variable) == 0x00001C, "Member 'bp_wi_OptionsVoice_C_Get_ActiveVivoxPlaybackDeviceOption::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_Get_ActiveVivoxPlaybackDeviceOption, CallFunc_Add_IntInt_ReturnValue) == 0x000020, "Member 'bp_wi_OptionsVoice_C_Get_ActiveVivoxPlaybackDeviceOption::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_Get_ActiveVivoxPlaybackDeviceOption, CallFunc_Map_Values_Values) == 0x000028, "Member 'bp_wi_OptionsVoice_C_Get_ActiveVivoxPlaybackDeviceOption::CallFunc_Map_Values_Values' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_Get_ActiveVivoxPlaybackDeviceOption, CallFunc_Map_Keys_Keys) == 0x000038, "Member 'bp_wi_OptionsVoice_C_Get_ActiveVivoxPlaybackDeviceOption::CallFunc_Map_Keys_Keys' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_Get_ActiveVivoxPlaybackDeviceOption, CallFunc_Array_Get_Item) == 0x000048, "Member 'bp_wi_OptionsVoice_C_Get_ActiveVivoxPlaybackDeviceOption::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_Get_ActiveVivoxPlaybackDeviceOption, CallFunc_EqualEqual_StrStr_ReturnValue) == 0x000058, "Member 'bp_wi_OptionsVoice_C_Get_ActiveVivoxPlaybackDeviceOption::CallFunc_EqualEqual_StrStr_ReturnValue' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_Get_ActiveVivoxPlaybackDeviceOption, CallFunc_Array_Length_ReturnValue) == 0x00005C, "Member 'bp_wi_OptionsVoice_C_Get_ActiveVivoxPlaybackDeviceOption::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(bp_wi_OptionsVoice_C_Get_ActiveVivoxPlaybackDeviceOption, CallFunc_Less_IntInt_ReturnValue) == 0x000060, "Member 'bp_wi_OptionsVoice_C_Get_ActiveVivoxPlaybackDeviceOption::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");

}

