#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_AAS_Follower

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPI_AAS_Follower.BPI_AAS_Follower_C
// 0x0000 (0x0028 - 0x0028)
class IBPI_AAS_Follower_C final : public IInterface
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BPI_AAS_Follower_C">();
	}
	static class IBPI_AAS_Follower_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IBPI_AAS_Follower_C>();
	}
};
static_assert(alignof(IBPI_AAS_Follower_C) == 0x000008, "Wrong alignment on IBPI_AAS_Follower_C");
static_assert(sizeof(IBPI_AAS_Follower_C) == 0x000028, "Wrong size on IBPI_AAS_Follower_C");

}

