#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CM_TabTitle

#include "Basic.hpp"

#include "CM_TabTitle_classes.hpp"
#include "CM_TabTitle_parameters.hpp"


namespace SDK
{

// Function CM_TabTitle.CM_TabTitle_C.ExecuteUbergraph_CM_TabTitle
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCM_TabTitle_C::ExecuteUbergraph_CM_TabTitle(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CM_TabTitle_C", "ExecuteUbergraph_CM_TabTitle");

	Params::CM_TabTitle_C_ExecuteUbergraph_CM_TabTitle Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CM_TabTitle.CM_TabTitle_C.Set Bottom Border Padding
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   In_Size_Y                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCM_TabTitle_C::Set_Bottom_Border_Padding(float In_Size_Y)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CM_TabTitle_C", "Set Bottom Border Padding");

	Params::CM_TabTitle_C_Set_Bottom_Border_Padding Parms{};

	Parms.In_Size_Y = In_Size_Y;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CM_TabTitle.CM_TabTitle_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UCM_TabTitle_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CM_TabTitle_C", "PreConstruct");

	Params::CM_TabTitle_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}

}

