#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DrownedEC

#include "Basic.hpp"

#include "SCT_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass DrownedEC.DrownedEC_C
// 0x0000 (0x0048 - 0x0048)
class UDrownedEC_C final : public UKillCalculationBase
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"DrownedEC_C">();
	}
	static class UDrownedEC_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDrownedEC_C>();
	}
};
static_assert(alignof(UDrownedEC_C) == 0x000008, "Wrong alignment on UDrownedEC_C");
static_assert(sizeof(UDrownedEC_C) == 0x000048, "Wrong size on UDrownedEC_C");

}

