#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FootstepType

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum FootstepType.FootstepType
// NumValues: 0x0008
enum class EFootstepType : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator4                           = 1,
	NewEnumerator5                           = 2,
	NewEnumerator6                           = 3,
	NewEnumerator3                           = 4,
	NewEnumerator7                           = 5,
	NewEnumerator8                           = 6,
	FootstepType_MAX                         = 7,
};

}

