#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: OnlineSubsystemEOSAuthDiscord

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// Class OnlineSubsystemEOSAuthDiscord.EOSNativePlatformDiscord
// 0x0008 (0x0030 - 0x0028)
class UEOSNativePlatformDiscord final : public UObject
{
public:
	uint8                                         Pad_28[0x8];                                       // 0x0028(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"EOSNativePlatformDiscord">();
	}
	static class UEOSNativePlatformDiscord* GetDefaultObj()
	{
		return GetDefaultObjImpl<UEOSNativePlatformDiscord>();
	}
};
static_assert(alignof(UEOSNativePlatformDiscord) == 0x000008, "Wrong alignment on UEOSNativePlatformDiscord");
static_assert(sizeof(UEOSNativePlatformDiscord) == 0x000030, "Wrong size on UEOSNativePlatformDiscord");

}

