#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: OtherPersonoidsList

#include "Basic.hpp"

#include "OtherPersonoidsList_classes.hpp"
#include "OtherPersonoidsList_parameters.hpp"


namespace SDK
{

// Function OtherPersonoidsList.OtherPersonoidsList_C.ExecuteUbergraph_OtherPersonoidsList
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UOtherPersonoidsList_C::ExecuteUbergraph_OtherPersonoidsList(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OtherPersonoidsList_C", "ExecuteUbergraph_OtherPersonoidsList");

	Params::OtherPersonoidsList_C_ExecuteUbergraph_OtherPersonoidsList Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function OtherPersonoidsList.OtherPersonoidsList_C.Initialize
// (BlueprintCallable, BlueprintEvent)

void UOtherPersonoidsList_C::Initialize()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OtherPersonoidsList_C", "Initialize");

	UObject::ProcessEvent(Func, nullptr);
}


// Function OtherPersonoidsList.OtherPersonoidsList_C.CacheOtherPersonoidsPlayerStates
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UOtherPersonoidsList_C::CacheOtherPersonoidsPlayerStates()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OtherPersonoidsList_C", "CacheOtherPersonoidsPlayerStates");

	UObject::ProcessEvent(Func, nullptr);
}


// Function OtherPersonoidsList.OtherPersonoidsList_C.Initialize Only Personoid
// (Public, BlueprintCallable, BlueprintEvent)

void UOtherPersonoidsList_C::Initialize_Only_Personoid()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OtherPersonoidsList_C", "Initialize Only Personoid");

	UObject::ProcessEvent(Func, nullptr);
}


// Function OtherPersonoidsList.OtherPersonoidsList_C.InitializeOtherPersonoids
// (Public, BlueprintCallable, BlueprintEvent)

void UOtherPersonoidsList_C::InitializeOtherPersonoids()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OtherPersonoidsList_C", "InitializeOtherPersonoids");

	UObject::ProcessEvent(Func, nullptr);
}


// Function OtherPersonoidsList.OtherPersonoidsList_C.InitializeHiddenPersonoids
// (Public, BlueprintCallable, BlueprintEvent)

void UOtherPersonoidsList_C::InitializeHiddenPersonoids()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OtherPersonoidsList_C", "InitializeHiddenPersonoids");

	UObject::ProcessEvent(Func, nullptr);
}

}

