#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PickupActor_FireExtinguisher

#include "Basic.hpp"

#include "PickupActor_FireExtinguisher_classes.hpp"
#include "PickupActor_FireExtinguisher_parameters.hpp"


namespace SDK
{

// Function PickupActor_FireExtinguisher.PickupActor_FireExtinguisher_C.ExecuteUbergraph_PickupActor_FireExtinguisher
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APickupActor_FireExtinguisher_C::ExecuteUbergraph_PickupActor_FireExtinguisher(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PickupActor_FireExtinguisher_C", "ExecuteUbergraph_PickupActor_FireExtinguisher");

	Params::PickupActor_FireExtinguisher_C_ExecuteUbergraph_PickupActor_FireExtinguisher Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PickupActor_FireExtinguisher.PickupActor_FireExtinguisher_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void APickupActor_FireExtinguisher_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PickupActor_FireExtinguisher_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PickupActor_FireExtinguisher.PickupActor_FireExtinguisher_C.Picked up
// (BlueprintCallable, BlueprintEvent)

void APickupActor_FireExtinguisher_C::Picked_up()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PickupActor_FireExtinguisher_C", "Picked up");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PickupActor_FireExtinguisher.PickupActor_FireExtinguisher_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void APickupActor_FireExtinguisher_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PickupActor_FireExtinguisher_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PickupActor_FireExtinguisher.PickupActor_FireExtinguisher_C.IsCloseToGroundBelow
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Close                                                  (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void APickupActor_FireExtinguisher_C::IsCloseToGroundBelow(bool* Close)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PickupActor_FireExtinguisher_C", "IsCloseToGroundBelow");

	Params::PickupActor_FireExtinguisher_C_IsCloseToGroundBelow Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Close != nullptr)
		*Close = Parms.Close;
}


// Function PickupActor_FireExtinguisher.PickupActor_FireExtinguisher_C.OnRep_WallMounted
// (BlueprintCallable, BlueprintEvent)

void APickupActor_FireExtinguisher_C::OnRep_WallMounted()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PickupActor_FireExtinguisher_C", "OnRep_WallMounted");

	UObject::ProcessEvent(Func, nullptr);
}

}

