#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SurveilanceCameraSCTBP

#include "Basic.hpp"

#include "SurveilanceCameraSCTBP_classes.hpp"
#include "SurveilanceCameraSCTBP_parameters.hpp"


namespace SDK
{

// Function SurveilanceCameraSCTBP.SurveilanceCameraSCTBP_C.ExecuteUbergraph_SurveilanceCameraSCTBP
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ASurveilanceCameraSCTBP_C::ExecuteUbergraph_SurveilanceCameraSCTBP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SurveilanceCameraSCTBP_C", "ExecuteUbergraph_SurveilanceCameraSCTBP");

	Params::SurveilanceCameraSCTBP_C_ExecuteUbergraph_SurveilanceCameraSCTBP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SurveilanceCameraSCTBP.SurveilanceCameraSCTBP_C.FlipStartEndView
// (BlueprintCallable, BlueprintEvent)

void ASurveilanceCameraSCTBP_C::FlipStartEndView()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SurveilanceCameraSCTBP_C", "FlipStartEndView");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SurveilanceCameraSCTBP.SurveilanceCameraSCTBP_C.StartPan
// (BlueprintCallable, BlueprintEvent)

void ASurveilanceCameraSCTBP_C::StartPan()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SurveilanceCameraSCTBP_C", "StartPan");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SurveilanceCameraSCTBP.SurveilanceCameraSCTBP_C.ReversePan
// (BlueprintCallable, BlueprintEvent)

void ASurveilanceCameraSCTBP_C::ReversePan()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SurveilanceCameraSCTBP_C", "ReversePan");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SurveilanceCameraSCTBP.SurveilanceCameraSCTBP_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ASurveilanceCameraSCTBP_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SurveilanceCameraSCTBP_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SurveilanceCameraSCTBP.SurveilanceCameraSCTBP_C.StopFollowTarget
// (BlueprintCallable, BlueprintEvent)

void ASurveilanceCameraSCTBP_C::StopFollowTarget()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SurveilanceCameraSCTBP_C", "StopFollowTarget");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SurveilanceCameraSCTBP.SurveilanceCameraSCTBP_C.FollowTarget
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           ViewTarget                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ASurveilanceCameraSCTBP_C::FollowTarget(class AActor* ViewTarget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SurveilanceCameraSCTBP_C", "FollowTarget");

	Params::SurveilanceCameraSCTBP_C_FollowTarget Parms{};

	Parms.ViewTarget = ViewTarget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SurveilanceCameraSCTBP.SurveilanceCameraSCTBP_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ASurveilanceCameraSCTBP_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SurveilanceCameraSCTBP_C", "ReceiveTick");

	Params::SurveilanceCameraSCTBP_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SurveilanceCameraSCTBP.SurveilanceCameraSCTBP_C.Pan__UpdateFunc
// (BlueprintEvent)

void ASurveilanceCameraSCTBP_C::Pan__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SurveilanceCameraSCTBP_C", "Pan__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SurveilanceCameraSCTBP.SurveilanceCameraSCTBP_C.Pan__FinishedFunc
// (BlueprintEvent)

void ASurveilanceCameraSCTBP_C::Pan__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SurveilanceCameraSCTBP_C", "Pan__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SurveilanceCameraSCTBP.SurveilanceCameraSCTBP_C.UserConstructionScript
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ASurveilanceCameraSCTBP_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SurveilanceCameraSCTBP_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SurveilanceCameraSCTBP.SurveilanceCameraSCTBP_C.SetViewTarget
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FVector                          Target                                                 (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ASurveilanceCameraSCTBP_C::SetViewTarget(const struct FVector& Target)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SurveilanceCameraSCTBP_C", "SetViewTarget");

	Params::SurveilanceCameraSCTBP_C_SetViewTarget Parms{};

	Parms.Target = std::move(Target);

	UObject::ProcessEvent(Func, &Parms);
}


// Function SurveilanceCameraSCTBP.SurveilanceCameraSCTBP_C.SwapVectors
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ASurveilanceCameraSCTBP_C::SwapVectors()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SurveilanceCameraSCTBP_C", "SwapVectors");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SurveilanceCameraSCTBP.SurveilanceCameraSCTBP_C.CameraActive
// (Public, BlueprintCallable, BlueprintEvent)

void ASurveilanceCameraSCTBP_C::CameraActive()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SurveilanceCameraSCTBP_C", "CameraActive");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SurveilanceCameraSCTBP.SurveilanceCameraSCTBP_C.CameraInactive
// (Public, BlueprintCallable, BlueprintEvent)

void ASurveilanceCameraSCTBP_C::CameraInactive()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SurveilanceCameraSCTBP_C", "CameraInactive");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SurveilanceCameraSCTBP.SurveilanceCameraSCTBP_C.RenderXray
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    On                                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ASurveilanceCameraSCTBP_C::RenderXray(bool On)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SurveilanceCameraSCTBP_C", "RenderXray");

	Params::SurveilanceCameraSCTBP_C_RenderXray Parms{};

	Parms.On = On;

	UObject::ProcessEvent(Func, &Parms);
}

}

