#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: bp_wi_AccelByte_ProtoMinusFriend_PopUp

#include "Basic.hpp"


namespace SDK::Params
{

// Function bp_wi_AccelByte_Proto-Friend_PopUp.bp_wi_AccelByte_Proto-Friend_PopUp_C.ExecuteUbergraph_bp_wi_AccelByte_Proto-Friend_PopUp
// 0x0020 (0x0020 - 0x0000)
struct bp_wi_AccelByte_ProtoMinusFriend_PopUp_C_ExecuteUbergraph_bp_wi_AccelByte_ProtoMinusFriend_PopUp final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Conv_StringToText_ReturnValue;            // 0x0008(0x0018)()
};
static_assert(alignof(bp_wi_AccelByte_ProtoMinusFriend_PopUp_C_ExecuteUbergraph_bp_wi_AccelByte_ProtoMinusFriend_PopUp) == 0x000008, "Wrong alignment on bp_wi_AccelByte_ProtoMinusFriend_PopUp_C_ExecuteUbergraph_bp_wi_AccelByte_ProtoMinusFriend_PopUp");
static_assert(sizeof(bp_wi_AccelByte_ProtoMinusFriend_PopUp_C_ExecuteUbergraph_bp_wi_AccelByte_ProtoMinusFriend_PopUp) == 0x000020, "Wrong size on bp_wi_AccelByte_ProtoMinusFriend_PopUp_C_ExecuteUbergraph_bp_wi_AccelByte_ProtoMinusFriend_PopUp");
static_assert(offsetof(bp_wi_AccelByte_ProtoMinusFriend_PopUp_C_ExecuteUbergraph_bp_wi_AccelByte_ProtoMinusFriend_PopUp, EntryPoint) == 0x000000, "Member 'bp_wi_AccelByte_ProtoMinusFriend_PopUp_C_ExecuteUbergraph_bp_wi_AccelByte_ProtoMinusFriend_PopUp::EntryPoint' has a wrong offset!");
static_assert(offsetof(bp_wi_AccelByte_ProtoMinusFriend_PopUp_C_ExecuteUbergraph_bp_wi_AccelByte_ProtoMinusFriend_PopUp, CallFunc_Conv_StringToText_ReturnValue) == 0x000008, "Member 'bp_wi_AccelByte_ProtoMinusFriend_PopUp_C_ExecuteUbergraph_bp_wi_AccelByte_ProtoMinusFriend_PopUp::CallFunc_Conv_StringToText_ReturnValue' has a wrong offset!");

}

