#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CharacterColliderBP_Cigarette

#include "Basic.hpp"

#include "CharacterColliderBP_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass CharacterColliderBP_Cigarette.CharacterColliderBP_Cigarette_C
// 0x0000 (0x0260 - 0x0260)
class ACharacterColliderBP_Cigarette_C final : public ACharacterColliderBP_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"CharacterColliderBP_Cigarette_C">();
	}
	static class ACharacterColliderBP_Cigarette_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ACharacterColliderBP_Cigarette_C>();
	}
};
static_assert(alignof(ACharacterColliderBP_Cigarette_C) == 0x000008, "Wrong alignment on ACharacterColliderBP_Cigarette_C");
static_assert(sizeof(ACharacterColliderBP_Cigarette_C) == 0x000260, "Wrong size on ACharacterColliderBP_Cigarette_C");

}

