#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CM_ContentDialogWrapper

#include "Basic.hpp"

#include "CM_ContentDialogWrapper_classes.hpp"
#include "CM_ContentDialogWrapper_parameters.hpp"


namespace SDK
{

// Function CM_ContentDialogWrapper.CM_ContentDialogWrapper_C.ExecuteUbergraph_CM_ContentDialogWrapper
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCM_ContentDialogWrapper_C::ExecuteUbergraph_CM_ContentDialogWrapper(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CM_ContentDialogWrapper_C", "ExecuteUbergraph_CM_ContentDialogWrapper");

	Params::CM_ContentDialogWrapper_C_ExecuteUbergraph_CM_ContentDialogWrapper Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CM_ContentDialogWrapper.CM_ContentDialogWrapper_C.OnFadeOut
// (BlueprintCallable, BlueprintEvent)

void UCM_ContentDialogWrapper_C::OnFadeOut()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CM_ContentDialogWrapper_C", "OnFadeOut");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CM_ContentDialogWrapper.CM_ContentDialogWrapper_C.OnFadeIn
// (BlueprintCallable, BlueprintEvent)

void UCM_ContentDialogWrapper_C::OnFadeIn()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CM_ContentDialogWrapper_C", "OnFadeIn");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CM_ContentDialogWrapper.CM_ContentDialogWrapper_C.OnStartFadeTransition
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Timer                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCM_ContentDialogWrapper_C::OnStartFadeTransition(float Timer)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CM_ContentDialogWrapper_C", "OnStartFadeTransition");

	Params::CM_ContentDialogWrapper_C_OnStartFadeTransition Parms{};

	Parms.Timer = Timer;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CM_ContentDialogWrapper.CM_ContentDialogWrapper_C.CloseDialog
// (BlueprintCallable, BlueprintEvent)

void UCM_ContentDialogWrapper_C::CloseDialog()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CM_ContentDialogWrapper_C", "CloseDialog");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CM_ContentDialogWrapper.CM_ContentDialogWrapper_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UCM_ContentDialogWrapper_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CM_ContentDialogWrapper_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CM_ContentDialogWrapper.CM_ContentDialogWrapper_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UCM_ContentDialogWrapper_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CM_ContentDialogWrapper_C", "PreConstruct");

	Params::CM_ContentDialogWrapper_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CM_ContentDialogWrapper.CM_ContentDialogWrapper_C.Add Content
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UUserWidget*                      Widget                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCM_ContentDialogWrapper_C::Add_Content(class UUserWidget* Widget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CM_ContentDialogWrapper_C", "Add Content");

	Params::CM_ContentDialogWrapper_C_Add_Content Parms{};

	Parms.Widget = Widget;

	UObject::ProcessEvent(Func, &Parms);
}

}

