#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CM_SubMenuWI

#include "Basic.hpp"

#include "UMG_structs.hpp"
#include "SCT_structs.hpp"


namespace SDK::Params
{

// Function CM_SubMenuWI.CM_SubMenuWI_C.OnNavigate__DelegateSignature
// 0x0010 (0x0010 - 0x0000)
struct CM_SubMenuWI_C_OnNavigate__DelegateSignature final
{
public:
	class FString                                 Title;                                             // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
};
static_assert(alignof(CM_SubMenuWI_C_OnNavigate__DelegateSignature) == 0x000008, "Wrong alignment on CM_SubMenuWI_C_OnNavigate__DelegateSignature");
static_assert(sizeof(CM_SubMenuWI_C_OnNavigate__DelegateSignature) == 0x000010, "Wrong size on CM_SubMenuWI_C_OnNavigate__DelegateSignature");
static_assert(offsetof(CM_SubMenuWI_C_OnNavigate__DelegateSignature, Title) == 0x000000, "Member 'CM_SubMenuWI_C_OnNavigate__DelegateSignature::Title' has a wrong offset!");

// Function CM_SubMenuWI.CM_SubMenuWI_C.ExecuteUbergraph_CM_SubMenuWI
// 0x00F8 (0x00F8 - 0x0000)
struct CM_SubMenuWI_C_ExecuteUbergraph_CM_SubMenuWI final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0004(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_1;            // 0x0014(0x0010)(ZeroConstructor, NoDestructor)
	uint8                                         Pad_24[0x4];                                       // 0x0024(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue;          // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AClientEntryPCBP_C*                     K2Node_DynamicCast_AsClient_Entry_PCBP;            // 0x0030(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_39[0x7];                                       // 0x0039(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue_1;        // 0x0040(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AClientEntryPCBP_C*                     K2Node_DynamicCast_AsClient_Entry_PCBP_1;          // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_51[0x3];                                       // 0x0051(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0054(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UCM_SubMenuSelectionButtonWI_C*         CallFunc_Array_Get_Item;                           // 0x0058(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue;               // 0x0060(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0061(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_62[0x6];                                       // 0x0062(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue_2;        // 0x0068(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ASCTPlayerController_MatchBP_C*         K2Node_DynamicCast_AsSCTPlayer_Controller_Match_BP; // 0x0070(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x0078(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_79[0x7];                                       // 0x0079(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue_3;        // 0x0080(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ASCTPlayerController_WarmupBP_C*        K2Node_DynamicCast_AsSCTPlayer_Controller_Warmup_BP; // 0x0088(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_3;                     // 0x0090(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_91[0x7];                                       // 0x0091(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue_4;        // 0x0098(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_2;            // 0x00A0(0x0010)(ZeroConstructor, NoDestructor)
	class ASCTPlayerController_WarmupBP_C*        K2Node_DynamicCast_AsSCTPlayer_Controller_Warmup_BP_1; // 0x00B0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_4;                     // 0x00B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_B9[0x7];                                       // 0x00B9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class USubMenuSelectionButtonUserWidget*      CallFunc_AddMenuItemWithEvent_ReturnValue;         // 0x00C0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USubMenuSelectionButtonUserWidget*      CallFunc_AddMenuItemWithEvent_ReturnValue_1;       // 0x00C8(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USubMenuSelectionButtonUserWidget*      CallFunc_AddMenuItemWithEvent_ReturnValue_2;       // 0x00D0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USubMenuSelectionButtonUserWidget*      CallFunc_AddMenuItemWithEvent_ReturnValue_3;       // 0x00D8(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ASCTPlayerController_MatchBP_C*         K2Node_DynamicCast_AsSCTPlayer_Controller_Match_BP_1; // 0x00E0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_5;                     // 0x00E8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_E9[0x3];                                       // 0x00E9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_GetGameTimeInSeconds_ReturnValue;         // 0x00EC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsWidgetInActiveMenu_ReturnValue;         // 0x00F0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsWidgetInAnyMenu_ReturnValue;            // 0x00F1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x00F2(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsWidgetInActiveMenu_ReturnValue_1;       // 0x00F3(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsWidgetInAnyMenu_ReturnValue_1;          // 0x00F4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Not_PreBool_ReturnValue_1;                // 0x00F5(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(CM_SubMenuWI_C_ExecuteUbergraph_CM_SubMenuWI) == 0x000008, "Wrong alignment on CM_SubMenuWI_C_ExecuteUbergraph_CM_SubMenuWI");
static_assert(sizeof(CM_SubMenuWI_C_ExecuteUbergraph_CM_SubMenuWI) == 0x0000F8, "Wrong size on CM_SubMenuWI_C_ExecuteUbergraph_CM_SubMenuWI");
static_assert(offsetof(CM_SubMenuWI_C_ExecuteUbergraph_CM_SubMenuWI, EntryPoint) == 0x000000, "Member 'CM_SubMenuWI_C_ExecuteUbergraph_CM_SubMenuWI::EntryPoint' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_ExecuteUbergraph_CM_SubMenuWI, K2Node_CreateDelegate_OutputDelegate) == 0x000004, "Member 'CM_SubMenuWI_C_ExecuteUbergraph_CM_SubMenuWI::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_ExecuteUbergraph_CM_SubMenuWI, K2Node_CreateDelegate_OutputDelegate_1) == 0x000014, "Member 'CM_SubMenuWI_C_ExecuteUbergraph_CM_SubMenuWI::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_ExecuteUbergraph_CM_SubMenuWI, CallFunc_GetPlayerController_ReturnValue) == 0x000028, "Member 'CM_SubMenuWI_C_ExecuteUbergraph_CM_SubMenuWI::CallFunc_GetPlayerController_ReturnValue' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_ExecuteUbergraph_CM_SubMenuWI, K2Node_DynamicCast_AsClient_Entry_PCBP) == 0x000030, "Member 'CM_SubMenuWI_C_ExecuteUbergraph_CM_SubMenuWI::K2Node_DynamicCast_AsClient_Entry_PCBP' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_ExecuteUbergraph_CM_SubMenuWI, K2Node_DynamicCast_bSuccess) == 0x000038, "Member 'CM_SubMenuWI_C_ExecuteUbergraph_CM_SubMenuWI::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_ExecuteUbergraph_CM_SubMenuWI, CallFunc_GetPlayerController_ReturnValue_1) == 0x000040, "Member 'CM_SubMenuWI_C_ExecuteUbergraph_CM_SubMenuWI::CallFunc_GetPlayerController_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_ExecuteUbergraph_CM_SubMenuWI, K2Node_DynamicCast_AsClient_Entry_PCBP_1) == 0x000048, "Member 'CM_SubMenuWI_C_ExecuteUbergraph_CM_SubMenuWI::K2Node_DynamicCast_AsClient_Entry_PCBP_1' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_ExecuteUbergraph_CM_SubMenuWI, K2Node_DynamicCast_bSuccess_1) == 0x000050, "Member 'CM_SubMenuWI_C_ExecuteUbergraph_CM_SubMenuWI::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_ExecuteUbergraph_CM_SubMenuWI, CallFunc_Array_Length_ReturnValue) == 0x000054, "Member 'CM_SubMenuWI_C_ExecuteUbergraph_CM_SubMenuWI::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_ExecuteUbergraph_CM_SubMenuWI, CallFunc_Array_Get_Item) == 0x000058, "Member 'CM_SubMenuWI_C_ExecuteUbergraph_CM_SubMenuWI::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_ExecuteUbergraph_CM_SubMenuWI, CallFunc_Greater_IntInt_ReturnValue) == 0x000060, "Member 'CM_SubMenuWI_C_ExecuteUbergraph_CM_SubMenuWI::CallFunc_Greater_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_ExecuteUbergraph_CM_SubMenuWI, K2Node_Event_IsDesignTime) == 0x000061, "Member 'CM_SubMenuWI_C_ExecuteUbergraph_CM_SubMenuWI::K2Node_Event_IsDesignTime' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_ExecuteUbergraph_CM_SubMenuWI, CallFunc_GetPlayerController_ReturnValue_2) == 0x000068, "Member 'CM_SubMenuWI_C_ExecuteUbergraph_CM_SubMenuWI::CallFunc_GetPlayerController_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_ExecuteUbergraph_CM_SubMenuWI, K2Node_DynamicCast_AsSCTPlayer_Controller_Match_BP) == 0x000070, "Member 'CM_SubMenuWI_C_ExecuteUbergraph_CM_SubMenuWI::K2Node_DynamicCast_AsSCTPlayer_Controller_Match_BP' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_ExecuteUbergraph_CM_SubMenuWI, K2Node_DynamicCast_bSuccess_2) == 0x000078, "Member 'CM_SubMenuWI_C_ExecuteUbergraph_CM_SubMenuWI::K2Node_DynamicCast_bSuccess_2' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_ExecuteUbergraph_CM_SubMenuWI, CallFunc_GetPlayerController_ReturnValue_3) == 0x000080, "Member 'CM_SubMenuWI_C_ExecuteUbergraph_CM_SubMenuWI::CallFunc_GetPlayerController_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_ExecuteUbergraph_CM_SubMenuWI, K2Node_DynamicCast_AsSCTPlayer_Controller_Warmup_BP) == 0x000088, "Member 'CM_SubMenuWI_C_ExecuteUbergraph_CM_SubMenuWI::K2Node_DynamicCast_AsSCTPlayer_Controller_Warmup_BP' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_ExecuteUbergraph_CM_SubMenuWI, K2Node_DynamicCast_bSuccess_3) == 0x000090, "Member 'CM_SubMenuWI_C_ExecuteUbergraph_CM_SubMenuWI::K2Node_DynamicCast_bSuccess_3' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_ExecuteUbergraph_CM_SubMenuWI, CallFunc_GetPlayerController_ReturnValue_4) == 0x000098, "Member 'CM_SubMenuWI_C_ExecuteUbergraph_CM_SubMenuWI::CallFunc_GetPlayerController_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_ExecuteUbergraph_CM_SubMenuWI, K2Node_CreateDelegate_OutputDelegate_2) == 0x0000A0, "Member 'CM_SubMenuWI_C_ExecuteUbergraph_CM_SubMenuWI::K2Node_CreateDelegate_OutputDelegate_2' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_ExecuteUbergraph_CM_SubMenuWI, K2Node_DynamicCast_AsSCTPlayer_Controller_Warmup_BP_1) == 0x0000B0, "Member 'CM_SubMenuWI_C_ExecuteUbergraph_CM_SubMenuWI::K2Node_DynamicCast_AsSCTPlayer_Controller_Warmup_BP_1' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_ExecuteUbergraph_CM_SubMenuWI, K2Node_DynamicCast_bSuccess_4) == 0x0000B8, "Member 'CM_SubMenuWI_C_ExecuteUbergraph_CM_SubMenuWI::K2Node_DynamicCast_bSuccess_4' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_ExecuteUbergraph_CM_SubMenuWI, CallFunc_AddMenuItemWithEvent_ReturnValue) == 0x0000C0, "Member 'CM_SubMenuWI_C_ExecuteUbergraph_CM_SubMenuWI::CallFunc_AddMenuItemWithEvent_ReturnValue' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_ExecuteUbergraph_CM_SubMenuWI, CallFunc_AddMenuItemWithEvent_ReturnValue_1) == 0x0000C8, "Member 'CM_SubMenuWI_C_ExecuteUbergraph_CM_SubMenuWI::CallFunc_AddMenuItemWithEvent_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_ExecuteUbergraph_CM_SubMenuWI, CallFunc_AddMenuItemWithEvent_ReturnValue_2) == 0x0000D0, "Member 'CM_SubMenuWI_C_ExecuteUbergraph_CM_SubMenuWI::CallFunc_AddMenuItemWithEvent_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_ExecuteUbergraph_CM_SubMenuWI, CallFunc_AddMenuItemWithEvent_ReturnValue_3) == 0x0000D8, "Member 'CM_SubMenuWI_C_ExecuteUbergraph_CM_SubMenuWI::CallFunc_AddMenuItemWithEvent_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_ExecuteUbergraph_CM_SubMenuWI, K2Node_DynamicCast_AsSCTPlayer_Controller_Match_BP_1) == 0x0000E0, "Member 'CM_SubMenuWI_C_ExecuteUbergraph_CM_SubMenuWI::K2Node_DynamicCast_AsSCTPlayer_Controller_Match_BP_1' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_ExecuteUbergraph_CM_SubMenuWI, K2Node_DynamicCast_bSuccess_5) == 0x0000E8, "Member 'CM_SubMenuWI_C_ExecuteUbergraph_CM_SubMenuWI::K2Node_DynamicCast_bSuccess_5' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_ExecuteUbergraph_CM_SubMenuWI, CallFunc_GetGameTimeInSeconds_ReturnValue) == 0x0000EC, "Member 'CM_SubMenuWI_C_ExecuteUbergraph_CM_SubMenuWI::CallFunc_GetGameTimeInSeconds_ReturnValue' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_ExecuteUbergraph_CM_SubMenuWI, CallFunc_IsWidgetInActiveMenu_ReturnValue) == 0x0000F0, "Member 'CM_SubMenuWI_C_ExecuteUbergraph_CM_SubMenuWI::CallFunc_IsWidgetInActiveMenu_ReturnValue' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_ExecuteUbergraph_CM_SubMenuWI, CallFunc_IsWidgetInAnyMenu_ReturnValue) == 0x0000F1, "Member 'CM_SubMenuWI_C_ExecuteUbergraph_CM_SubMenuWI::CallFunc_IsWidgetInAnyMenu_ReturnValue' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_ExecuteUbergraph_CM_SubMenuWI, CallFunc_Not_PreBool_ReturnValue) == 0x0000F2, "Member 'CM_SubMenuWI_C_ExecuteUbergraph_CM_SubMenuWI::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_ExecuteUbergraph_CM_SubMenuWI, CallFunc_IsWidgetInActiveMenu_ReturnValue_1) == 0x0000F3, "Member 'CM_SubMenuWI_C_ExecuteUbergraph_CM_SubMenuWI::CallFunc_IsWidgetInActiveMenu_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_ExecuteUbergraph_CM_SubMenuWI, CallFunc_IsWidgetInAnyMenu_ReturnValue_1) == 0x0000F4, "Member 'CM_SubMenuWI_C_ExecuteUbergraph_CM_SubMenuWI::CallFunc_IsWidgetInAnyMenu_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_ExecuteUbergraph_CM_SubMenuWI, CallFunc_Not_PreBool_ReturnValue_1) == 0x0000F5, "Member 'CM_SubMenuWI_C_ExecuteUbergraph_CM_SubMenuWI::CallFunc_Not_PreBool_ReturnValue_1' has a wrong offset!");

// Function CM_SubMenuWI.CM_SubMenuWI_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct CM_SubMenuWI_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(CM_SubMenuWI_C_PreConstruct) == 0x000001, "Wrong alignment on CM_SubMenuWI_C_PreConstruct");
static_assert(sizeof(CM_SubMenuWI_C_PreConstruct) == 0x000001, "Wrong size on CM_SubMenuWI_C_PreConstruct");
static_assert(offsetof(CM_SubMenuWI_C_PreConstruct, IsDesignTime) == 0x000000, "Member 'CM_SubMenuWI_C_PreConstruct::IsDesignTime' has a wrong offset!");

// Function CM_SubMenuWI.CM_SubMenuWI_C.AddMenuItem
// 0x0070 (0x0070 - 0x0000)
struct CM_SubMenuWI_C_AddMenuItem final
{
public:
	class FText                                   Title;                                             // 0x0000(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm)
	float                                         Width;                                             // 0x0018(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1C[0x4];                                       // 0x001C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UCM_SubMenuSelectionButtonWI_C*         MenuItem;                                          // 0x0020(0x0008)(Parm, OutParm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UImage*                                 BGImage;                                           // 0x0028(0x0008)(Edit, BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UOverlay*                               InOverlay;                                         // 0x0030(0x0008)(Edit, BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UCM_SubMenuSelectionButtonWI_C*         CallFunc_Create_ReturnValue;                       // 0x0038(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Add_ReturnValue;                    // 0x0040(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_44[0x4];                                       // 0x0044(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UOverlaySlot*                           CallFunc_AddChildToOverlay_ReturnValue;            // 0x0048(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UImage*                                 CallFunc_SpawnObject_ReturnValue;                  // 0x0050(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UOverlay*                               CallFunc_SpawnObject_ReturnValue_1;                // 0x0058(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	class UOverlaySlot*                           CallFunc_AddChildToOverlay_ReturnValue_1;          // 0x0060(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UHorizontalBoxSlot*                     CallFunc_AddChildToHorizontalBox_ReturnValue;      // 0x0068(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(CM_SubMenuWI_C_AddMenuItem) == 0x000008, "Wrong alignment on CM_SubMenuWI_C_AddMenuItem");
static_assert(sizeof(CM_SubMenuWI_C_AddMenuItem) == 0x000070, "Wrong size on CM_SubMenuWI_C_AddMenuItem");
static_assert(offsetof(CM_SubMenuWI_C_AddMenuItem, Title) == 0x000000, "Member 'CM_SubMenuWI_C_AddMenuItem::Title' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_AddMenuItem, Width) == 0x000018, "Member 'CM_SubMenuWI_C_AddMenuItem::Width' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_AddMenuItem, MenuItem) == 0x000020, "Member 'CM_SubMenuWI_C_AddMenuItem::MenuItem' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_AddMenuItem, BGImage) == 0x000028, "Member 'CM_SubMenuWI_C_AddMenuItem::BGImage' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_AddMenuItem, InOverlay) == 0x000030, "Member 'CM_SubMenuWI_C_AddMenuItem::InOverlay' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_AddMenuItem, CallFunc_Create_ReturnValue) == 0x000038, "Member 'CM_SubMenuWI_C_AddMenuItem::CallFunc_Create_ReturnValue' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_AddMenuItem, CallFunc_Array_Add_ReturnValue) == 0x000040, "Member 'CM_SubMenuWI_C_AddMenuItem::CallFunc_Array_Add_ReturnValue' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_AddMenuItem, CallFunc_AddChildToOverlay_ReturnValue) == 0x000048, "Member 'CM_SubMenuWI_C_AddMenuItem::CallFunc_AddChildToOverlay_ReturnValue' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_AddMenuItem, CallFunc_SpawnObject_ReturnValue) == 0x000050, "Member 'CM_SubMenuWI_C_AddMenuItem::CallFunc_SpawnObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_AddMenuItem, CallFunc_SpawnObject_ReturnValue_1) == 0x000058, "Member 'CM_SubMenuWI_C_AddMenuItem::CallFunc_SpawnObject_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_AddMenuItem, CallFunc_AddChildToOverlay_ReturnValue_1) == 0x000060, "Member 'CM_SubMenuWI_C_AddMenuItem::CallFunc_AddChildToOverlay_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_AddMenuItem, CallFunc_AddChildToHorizontalBox_ReturnValue) == 0x000068, "Member 'CM_SubMenuWI_C_AddMenuItem::CallFunc_AddChildToHorizontalBox_ReturnValue' has a wrong offset!");

// Function CM_SubMenuWI.CM_SubMenuWI_C.SetActiveWidgetSelectionAsSelected
// 0x0028 (0x0028 - 0x0000)
struct CM_SubMenuWI_C_SetActiveWidgetSelectionAsSelected final
{
public:
	class UCM_SubMenuSelectionButtonWI_C*         SelectionButton;                                   // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x000C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_D[0x3];                                        // 0x000D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0014(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_15[0x3];                                       // 0x0015(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UCM_HorizontalSelectionButtonWI_C*      CallFunc_Array_Get_Item;                           // 0x0020(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(CM_SubMenuWI_C_SetActiveWidgetSelectionAsSelected) == 0x000008, "Wrong alignment on CM_SubMenuWI_C_SetActiveWidgetSelectionAsSelected");
static_assert(sizeof(CM_SubMenuWI_C_SetActiveWidgetSelectionAsSelected) == 0x000028, "Wrong size on CM_SubMenuWI_C_SetActiveWidgetSelectionAsSelected");
static_assert(offsetof(CM_SubMenuWI_C_SetActiveWidgetSelectionAsSelected, SelectionButton) == 0x000000, "Member 'CM_SubMenuWI_C_SetActiveWidgetSelectionAsSelected::SelectionButton' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_SetActiveWidgetSelectionAsSelected, CallFunc_Array_Length_ReturnValue) == 0x000008, "Member 'CM_SubMenuWI_C_SetActiveWidgetSelectionAsSelected::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_SetActiveWidgetSelectionAsSelected, CallFunc_IsValid_ReturnValue) == 0x00000C, "Member 'CM_SubMenuWI_C_SetActiveWidgetSelectionAsSelected::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_SetActiveWidgetSelectionAsSelected, Temp_int_Loop_Counter_Variable) == 0x000010, "Member 'CM_SubMenuWI_C_SetActiveWidgetSelectionAsSelected::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_SetActiveWidgetSelectionAsSelected, CallFunc_Less_IntInt_ReturnValue) == 0x000014, "Member 'CM_SubMenuWI_C_SetActiveWidgetSelectionAsSelected::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_SetActiveWidgetSelectionAsSelected, CallFunc_Add_IntInt_ReturnValue) == 0x000018, "Member 'CM_SubMenuWI_C_SetActiveWidgetSelectionAsSelected::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_SetActiveWidgetSelectionAsSelected, Temp_int_Array_Index_Variable) == 0x00001C, "Member 'CM_SubMenuWI_C_SetActiveWidgetSelectionAsSelected::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_SetActiveWidgetSelectionAsSelected, CallFunc_Array_Get_Item) == 0x000020, "Member 'CM_SubMenuWI_C_SetActiveWidgetSelectionAsSelected::CallFunc_Array_Get_Item' has a wrong offset!");

// Function CM_SubMenuWI.CM_SubMenuWI_C.NavigateSubMenu
// 0x0040 (0x0040 - 0x0000)
struct CM_SubMenuWI_C_NavigateSubMenu final
{
public:
	bool                                          Right;                                             // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable;                                // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2[0x2];                                        // 0x0002(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Variable;                                 // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_1;                               // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetActiveWidgetIndex_ReturnValue;         // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_Select_Default;                             // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Conv_IntToString_ReturnValue;             // 0x0018(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x002C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Subtract_IntInt_ReturnValue;              // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Clamp_ReturnValue;                        // 0x0034(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_1;               // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue;               // 0x003C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(CM_SubMenuWI_C_NavigateSubMenu) == 0x000008, "Wrong alignment on CM_SubMenuWI_C_NavigateSubMenu");
static_assert(sizeof(CM_SubMenuWI_C_NavigateSubMenu) == 0x000040, "Wrong size on CM_SubMenuWI_C_NavigateSubMenu");
static_assert(offsetof(CM_SubMenuWI_C_NavigateSubMenu, Right) == 0x000000, "Member 'CM_SubMenuWI_C_NavigateSubMenu::Right' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_NavigateSubMenu, Temp_bool_Variable) == 0x000001, "Member 'CM_SubMenuWI_C_NavigateSubMenu::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_NavigateSubMenu, Temp_int_Variable) == 0x000004, "Member 'CM_SubMenuWI_C_NavigateSubMenu::Temp_int_Variable' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_NavigateSubMenu, Temp_int_Variable_1) == 0x000008, "Member 'CM_SubMenuWI_C_NavigateSubMenu::Temp_int_Variable_1' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_NavigateSubMenu, CallFunc_GetActiveWidgetIndex_ReturnValue) == 0x00000C, "Member 'CM_SubMenuWI_C_NavigateSubMenu::CallFunc_GetActiveWidgetIndex_ReturnValue' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_NavigateSubMenu, K2Node_Select_Default) == 0x000010, "Member 'CM_SubMenuWI_C_NavigateSubMenu::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_NavigateSubMenu, CallFunc_Conv_IntToString_ReturnValue) == 0x000018, "Member 'CM_SubMenuWI_C_NavigateSubMenu::CallFunc_Conv_IntToString_ReturnValue' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_NavigateSubMenu, CallFunc_Array_Length_ReturnValue) == 0x000028, "Member 'CM_SubMenuWI_C_NavigateSubMenu::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_NavigateSubMenu, CallFunc_Add_IntInt_ReturnValue) == 0x00002C, "Member 'CM_SubMenuWI_C_NavigateSubMenu::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_NavigateSubMenu, CallFunc_Subtract_IntInt_ReturnValue) == 0x000030, "Member 'CM_SubMenuWI_C_NavigateSubMenu::CallFunc_Subtract_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_NavigateSubMenu, CallFunc_Clamp_ReturnValue) == 0x000034, "Member 'CM_SubMenuWI_C_NavigateSubMenu::CallFunc_Clamp_ReturnValue' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_NavigateSubMenu, CallFunc_Array_Length_ReturnValue_1) == 0x000038, "Member 'CM_SubMenuWI_C_NavigateSubMenu::CallFunc_Array_Length_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_NavigateSubMenu, CallFunc_Greater_IntInt_ReturnValue) == 0x00003C, "Member 'CM_SubMenuWI_C_NavigateSubMenu::CallFunc_Greater_IntInt_ReturnValue' has a wrong offset!");

// Function CM_SubMenuWI.CM_SubMenuWI_C.Navigate Sub Menu to Specific
// 0x0048 (0x0048 - 0x0000)
struct CM_SubMenuWI_C_Navigate_Sub_Menu_to_Specific final
{
public:
	int32                                         Index_0;                                           // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UCM_SubMenuSelectionButtonWI_C*         CallFunc_Array_Get_Item;                           // 0x0008(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_GetText_ReturnValue;                      // 0x0018(0x0018)()
	bool                                          CallFunc_Greater_IntInt_ReturnValue;               // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_31[0x7];                                       // 0x0031(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Conv_TextToString_ReturnValue;            // 0x0038(0x0010)(ZeroConstructor, HasGetValueTypeHash)
};
static_assert(alignof(CM_SubMenuWI_C_Navigate_Sub_Menu_to_Specific) == 0x000008, "Wrong alignment on CM_SubMenuWI_C_Navigate_Sub_Menu_to_Specific");
static_assert(sizeof(CM_SubMenuWI_C_Navigate_Sub_Menu_to_Specific) == 0x000048, "Wrong size on CM_SubMenuWI_C_Navigate_Sub_Menu_to_Specific");
static_assert(offsetof(CM_SubMenuWI_C_Navigate_Sub_Menu_to_Specific, Index_0) == 0x000000, "Member 'CM_SubMenuWI_C_Navigate_Sub_Menu_to_Specific::Index_0' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_Navigate_Sub_Menu_to_Specific, CallFunc_Array_Get_Item) == 0x000008, "Member 'CM_SubMenuWI_C_Navigate_Sub_Menu_to_Specific::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_Navigate_Sub_Menu_to_Specific, CallFunc_Array_Length_ReturnValue) == 0x000010, "Member 'CM_SubMenuWI_C_Navigate_Sub_Menu_to_Specific::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_Navigate_Sub_Menu_to_Specific, CallFunc_GetText_ReturnValue) == 0x000018, "Member 'CM_SubMenuWI_C_Navigate_Sub_Menu_to_Specific::CallFunc_GetText_ReturnValue' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_Navigate_Sub_Menu_to_Specific, CallFunc_Greater_IntInt_ReturnValue) == 0x000030, "Member 'CM_SubMenuWI_C_Navigate_Sub_Menu_to_Specific::CallFunc_Greater_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_Navigate_Sub_Menu_to_Specific, CallFunc_Conv_TextToString_ReturnValue) == 0x000038, "Member 'CM_SubMenuWI_C_Navigate_Sub_Menu_to_Specific::CallFunc_Conv_TextToString_ReturnValue' has a wrong offset!");

// Function CM_SubMenuWI.CM_SubMenuWI_C.ManualSelectedIndexUpdate
// 0x0004 (0x0004 - 0x0000)
struct CM_SubMenuWI_C_ManualSelectedIndexUpdate final
{
public:
	int32                                         Index_0;                                           // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(CM_SubMenuWI_C_ManualSelectedIndexUpdate) == 0x000004, "Wrong alignment on CM_SubMenuWI_C_ManualSelectedIndexUpdate");
static_assert(sizeof(CM_SubMenuWI_C_ManualSelectedIndexUpdate) == 0x000004, "Wrong size on CM_SubMenuWI_C_ManualSelectedIndexUpdate");
static_assert(offsetof(CM_SubMenuWI_C_ManualSelectedIndexUpdate, Index_0) == 0x000000, "Member 'CM_SubMenuWI_C_ManualSelectedIndexUpdate::Index_0' has a wrong offset!");

// Function CM_SubMenuWI.CM_SubMenuWI_C.UpdateNavigationButtons
// 0x0007 (0x0007 - 0x0000)
struct CM_SubMenuWI_C_UpdateNavigationButtons final
{
public:
	bool                                          Temp_bool_Variable;                                // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              Temp_byte_Variable;                                // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_1;                              // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsUsingControllerOnPC_ReturnValue;        // 0x0003(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsConsolePlatform_ReturnValue;            // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              K2Node_Select_Default;                             // 0x0006(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(CM_SubMenuWI_C_UpdateNavigationButtons) == 0x000001, "Wrong alignment on CM_SubMenuWI_C_UpdateNavigationButtons");
static_assert(sizeof(CM_SubMenuWI_C_UpdateNavigationButtons) == 0x000007, "Wrong size on CM_SubMenuWI_C_UpdateNavigationButtons");
static_assert(offsetof(CM_SubMenuWI_C_UpdateNavigationButtons, Temp_bool_Variable) == 0x000000, "Member 'CM_SubMenuWI_C_UpdateNavigationButtons::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_UpdateNavigationButtons, Temp_byte_Variable) == 0x000001, "Member 'CM_SubMenuWI_C_UpdateNavigationButtons::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_UpdateNavigationButtons, Temp_byte_Variable_1) == 0x000002, "Member 'CM_SubMenuWI_C_UpdateNavigationButtons::Temp_byte_Variable_1' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_UpdateNavigationButtons, CallFunc_IsUsingControllerOnPC_ReturnValue) == 0x000003, "Member 'CM_SubMenuWI_C_UpdateNavigationButtons::CallFunc_IsUsingControllerOnPC_ReturnValue' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_UpdateNavigationButtons, CallFunc_IsConsolePlatform_ReturnValue) == 0x000004, "Member 'CM_SubMenuWI_C_UpdateNavigationButtons::CallFunc_IsConsolePlatform_ReturnValue' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_UpdateNavigationButtons, CallFunc_BooleanOR_ReturnValue) == 0x000005, "Member 'CM_SubMenuWI_C_UpdateNavigationButtons::CallFunc_BooleanOR_ReturnValue' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_UpdateNavigationButtons, K2Node_Select_Default) == 0x000006, "Member 'CM_SubMenuWI_C_UpdateNavigationButtons::K2Node_Select_Default' has a wrong offset!");

// Function CM_SubMenuWI.CM_SubMenuWI_C.SetNavigationButtonTextures
// 0x0004 (0x0004 - 0x0000)
struct CM_SubMenuWI_C_SetNavigationButtonTextures final
{
public:
	bool                                          CallFunc_IsXboxPlatform_ReturnValue;               // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsConsolePlatform_ReturnValue;            // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x0003(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(CM_SubMenuWI_C_SetNavigationButtonTextures) == 0x000001, "Wrong alignment on CM_SubMenuWI_C_SetNavigationButtonTextures");
static_assert(sizeof(CM_SubMenuWI_C_SetNavigationButtonTextures) == 0x000004, "Wrong size on CM_SubMenuWI_C_SetNavigationButtonTextures");
static_assert(offsetof(CM_SubMenuWI_C_SetNavigationButtonTextures, CallFunc_IsXboxPlatform_ReturnValue) == 0x000000, "Member 'CM_SubMenuWI_C_SetNavigationButtonTextures::CallFunc_IsXboxPlatform_ReturnValue' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_SetNavigationButtonTextures, CallFunc_IsConsolePlatform_ReturnValue) == 0x000001, "Member 'CM_SubMenuWI_C_SetNavigationButtonTextures::CallFunc_IsConsolePlatform_ReturnValue' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_SetNavigationButtonTextures, CallFunc_Not_PreBool_ReturnValue) == 0x000002, "Member 'CM_SubMenuWI_C_SetNavigationButtonTextures::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_SetNavigationButtonTextures, CallFunc_BooleanOR_ReturnValue) == 0x000003, "Member 'CM_SubMenuWI_C_SetNavigationButtonTextures::CallFunc_BooleanOR_ReturnValue' has a wrong offset!");

// Function CM_SubMenuWI.CM_SubMenuWI_C.SetXboxTexture
// 0x0018 (0x0018 - 0x0000)
struct CM_SubMenuWI_C_SetXboxTexture final
{
public:
	class UImage*                                 Target;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UTexture2D*                             CallFunc_GetXboxTexture_Value;                     // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetXboxTexture_Success;                   // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(CM_SubMenuWI_C_SetXboxTexture) == 0x000008, "Wrong alignment on CM_SubMenuWI_C_SetXboxTexture");
static_assert(sizeof(CM_SubMenuWI_C_SetXboxTexture) == 0x000018, "Wrong size on CM_SubMenuWI_C_SetXboxTexture");
static_assert(offsetof(CM_SubMenuWI_C_SetXboxTexture, Target) == 0x000000, "Member 'CM_SubMenuWI_C_SetXboxTexture::Target' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_SetXboxTexture, CallFunc_GetXboxTexture_Value) == 0x000008, "Member 'CM_SubMenuWI_C_SetXboxTexture::CallFunc_GetXboxTexture_Value' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_SetXboxTexture, CallFunc_GetXboxTexture_Success) == 0x000010, "Member 'CM_SubMenuWI_C_SetXboxTexture::CallFunc_GetXboxTexture_Success' has a wrong offset!");

// Function CM_SubMenuWI.CM_SubMenuWI_C.IsUsingControllerOnPC
// 0x0028 (0x0028 - 0x0000)
struct CM_SubMenuWI_C_IsUsingControllerOnPC final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UGameInstance*                          CallFunc_GetGameInstance_ReturnValue;              // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsConsolePlatform_ReturnValue;            // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class USCTGameInstance*                       K2Node_DynamicCast_AsSCTGame_Instance;             // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0021(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESCTControllerType                            CallFunc_GetLastControllerType_ReturnValue;        // 0x0022(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_ByteByte_ReturnValue;            // 0x0023(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(CM_SubMenuWI_C_IsUsingControllerOnPC) == 0x000008, "Wrong alignment on CM_SubMenuWI_C_IsUsingControllerOnPC");
static_assert(sizeof(CM_SubMenuWI_C_IsUsingControllerOnPC) == 0x000028, "Wrong size on CM_SubMenuWI_C_IsUsingControllerOnPC");
static_assert(offsetof(CM_SubMenuWI_C_IsUsingControllerOnPC, ReturnValue) == 0x000000, "Member 'CM_SubMenuWI_C_IsUsingControllerOnPC::ReturnValue' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_IsUsingControllerOnPC, CallFunc_GetGameInstance_ReturnValue) == 0x000008, "Member 'CM_SubMenuWI_C_IsUsingControllerOnPC::CallFunc_GetGameInstance_ReturnValue' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_IsUsingControllerOnPC, CallFunc_IsConsolePlatform_ReturnValue) == 0x000010, "Member 'CM_SubMenuWI_C_IsUsingControllerOnPC::CallFunc_IsConsolePlatform_ReturnValue' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_IsUsingControllerOnPC, K2Node_DynamicCast_AsSCTGame_Instance) == 0x000018, "Member 'CM_SubMenuWI_C_IsUsingControllerOnPC::K2Node_DynamicCast_AsSCTGame_Instance' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_IsUsingControllerOnPC, K2Node_DynamicCast_bSuccess) == 0x000020, "Member 'CM_SubMenuWI_C_IsUsingControllerOnPC::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_IsUsingControllerOnPC, CallFunc_Not_PreBool_ReturnValue) == 0x000021, "Member 'CM_SubMenuWI_C_IsUsingControllerOnPC::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_IsUsingControllerOnPC, CallFunc_GetLastControllerType_ReturnValue) == 0x000022, "Member 'CM_SubMenuWI_C_IsUsingControllerOnPC::CallFunc_GetLastControllerType_ReturnValue' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_IsUsingControllerOnPC, CallFunc_NotEqual_ByteByte_ReturnValue) == 0x000023, "Member 'CM_SubMenuWI_C_IsUsingControllerOnPC::CallFunc_NotEqual_ByteByte_ReturnValue' has a wrong offset!");

// Function CM_SubMenuWI.CM_SubMenuWI_C.GetXboxTexture
// 0x0038 (0x0038 - 0x0000)
struct CM_SubMenuWI_C_GetXboxTexture final
{
public:
	class UImage*                                 Target;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UTexture2D*                             Value;                                             // 0x0008(0x0008)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Success;                                           // 0x0010(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UTexture2D*                             K2Node_DynamicCast_AsTexture_2D;                   // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UTexture2D*                             CallFunc_Map_Find_Value;                           // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Map_Find_ReturnValue;                     // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(CM_SubMenuWI_C_GetXboxTexture) == 0x000008, "Wrong alignment on CM_SubMenuWI_C_GetXboxTexture");
static_assert(sizeof(CM_SubMenuWI_C_GetXboxTexture) == 0x000038, "Wrong size on CM_SubMenuWI_C_GetXboxTexture");
static_assert(offsetof(CM_SubMenuWI_C_GetXboxTexture, Target) == 0x000000, "Member 'CM_SubMenuWI_C_GetXboxTexture::Target' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_GetXboxTexture, Value) == 0x000008, "Member 'CM_SubMenuWI_C_GetXboxTexture::Value' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_GetXboxTexture, Success) == 0x000010, "Member 'CM_SubMenuWI_C_GetXboxTexture::Success' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_GetXboxTexture, K2Node_DynamicCast_AsTexture_2D) == 0x000018, "Member 'CM_SubMenuWI_C_GetXboxTexture::K2Node_DynamicCast_AsTexture_2D' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_GetXboxTexture, K2Node_DynamicCast_bSuccess) == 0x000020, "Member 'CM_SubMenuWI_C_GetXboxTexture::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_GetXboxTexture, CallFunc_Map_Find_Value) == 0x000028, "Member 'CM_SubMenuWI_C_GetXboxTexture::CallFunc_Map_Find_Value' has a wrong offset!");
static_assert(offsetof(CM_SubMenuWI_C_GetXboxTexture, CallFunc_Map_Find_ReturnValue) == 0x000030, "Member 'CM_SubMenuWI_C_GetXboxTexture::CallFunc_Map_Find_ReturnValue' has a wrong offset!");

}

