#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EmergencyMeetingLevelLoad

#include "Basic.hpp"

#include "EmergencyMeetingSCTBP_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass EmergencyMeetingLevelLoad.EmergencyMeetingLevelLoad_C
// 0x0010 (0x04A0 - 0x0490)
class AEmergencyMeetingLevelLoad_C final : public AEmergencyMeetingSCTBP_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_EmergencyMeetingLevelLoad_C;        // 0x0490(0x0008)(ZeroConstructor, Transient, DuplicateTransient, UObjectWrapper)

public:
	void ExecuteUbergraph_EmergencyMeetingLevelLoad(int32 EntryPoint);
	void Set_Oxygen();
	void InitiateEndMeeting();
	void Start();
	void GetInitiatingCharacters(TArray<class ACharacter*>* Characters);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"EmergencyMeetingLevelLoad_C">();
	}
	static class AEmergencyMeetingLevelLoad_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AEmergencyMeetingLevelLoad_C>();
	}
};
static_assert(alignof(AEmergencyMeetingLevelLoad_C) == 0x000010, "Wrong alignment on AEmergencyMeetingLevelLoad_C");
static_assert(sizeof(AEmergencyMeetingLevelLoad_C) == 0x0004A0, "Wrong size on AEmergencyMeetingLevelLoad_C");
static_assert(offsetof(AEmergencyMeetingLevelLoad_C, UberGraphFrame_EmergencyMeetingLevelLoad_C) == 0x000490, "Member 'AEmergencyMeetingLevelLoad_C::UberGraphFrame_EmergencyMeetingLevelLoad_C' has a wrong offset!");

}

