#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PersonoidMainMenuSCTBP

#include "Basic.hpp"

#include "PersonoidMainMenuSCTBP_classes.hpp"
#include "PersonoidMainMenuSCTBP_parameters.hpp"


namespace SDK
{

// Function PersonoidMainMenuSCTBP.PersonoidMainMenuSCTBP_C.ExecuteUbergraph_PersonoidMainMenuSCTBP
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APersonoidMainMenuSCTBP_C::ExecuteUbergraph_PersonoidMainMenuSCTBP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PersonoidMainMenuSCTBP_C", "ExecuteUbergraph_PersonoidMainMenuSCTBP");

	Params::PersonoidMainMenuSCTBP_C_ExecuteUbergraph_PersonoidMainMenuSCTBP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PersonoidMainMenuSCTBP.PersonoidMainMenuSCTBP_C.Audio Transform
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Reverse                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void APersonoidMainMenuSCTBP_C::Audio_Transform(bool Reverse)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PersonoidMainMenuSCTBP_C", "Audio Transform");

	Params::PersonoidMainMenuSCTBP_C_Audio_Transform Parms{};

	Parms.Reverse = Reverse;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PersonoidMainMenuSCTBP.PersonoidMainMenuSCTBP_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void APersonoidMainMenuSCTBP_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PersonoidMainMenuSCTBP_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PersonoidMainMenuSCTBP.PersonoidMainMenuSCTBP_C.Lerp__UpdateFunc
// (BlueprintEvent)

void APersonoidMainMenuSCTBP_C::Lerp__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PersonoidMainMenuSCTBP_C", "Lerp__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PersonoidMainMenuSCTBP.PersonoidMainMenuSCTBP_C.Lerp__FinishedFunc
// (BlueprintEvent)

void APersonoidMainMenuSCTBP_C::Lerp__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PersonoidMainMenuSCTBP_C", "Lerp__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PersonoidMainMenuSCTBP.PersonoidMainMenuSCTBP_C.UserConstructionScript
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void APersonoidMainMenuSCTBP_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PersonoidMainMenuSCTBP_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

