#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PickUpItemWI

#include "Basic.hpp"

#include "PickUpItemWI_classes.hpp"
#include "PickUpItemWI_parameters.hpp"


namespace SDK
{

// Function PickUpItemWI.PickUpItemWI_C.ExecuteUbergraph_PickUpItemWI
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPickUpItemWI_C::ExecuteUbergraph_PickUpItemWI(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PickUpItemWI_C", "ExecuteUbergraph_PickUpItemWI");

	Params::PickUpItemWI_C_ExecuteUbergraph_PickUpItemWI Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PickUpItemWI.PickUpItemWI_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UPickUpItemWI_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PickUpItemWI_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PickUpItemWI.PickUpItemWI_C.OnEndAnimation
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UCanvasPanel*                     Canvas_Floating_0                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPickUpItemWI_C::OnEndAnimation(class UCanvasPanel* Canvas_Floating_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PickUpItemWI_C", "OnEndAnimation");

	Params::PickUpItemWI_C_OnEndAnimation Parms{};

	Parms.Canvas_Floating_0 = Canvas_Floating_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PickUpItemWI.PickUpItemWI_C.GetCentreOfViewport
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FVector2D                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

struct FVector2D UPickUpItemWI_C::GetCentreOfViewport()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PickUpItemWI_C", "GetCentreOfViewport");

	Params::PickUpItemWI_C_GetCentreOfViewport Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function PickUpItemWI.PickUpItemWI_C.ProjectCSMToScreen
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class UContextStaticMeshComponent*      CSM                                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FVector2D                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

struct FVector2D UPickUpItemWI_C::ProjectCSMToScreen(class UContextStaticMeshComponent* CSM)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PickUpItemWI_C", "ProjectCSMToScreen");

	Params::PickUpItemWI_C_ProjectCSMToScreen Parms{};

	Parms.CSM = CSM;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function PickUpItemWI.PickUpItemWI_C.ProjectActorToScreen
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class AActor*                           Actor                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FVector                          Offset                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FVector2D                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

struct FVector2D UPickUpItemWI_C::ProjectActorToScreen(class AActor* Actor, const struct FVector& Offset)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PickUpItemWI_C", "ProjectActorToScreen");

	Params::PickUpItemWI_C_ProjectActorToScreen Parms{};

	Parms.Actor = Actor;
	Parms.Offset = std::move(Offset);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function PickUpItemWI.PickUpItemWI_C.SequenceEvent__ENTRYPOINTPickUpItemWI_0
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UCanvasPanel*                     Canvas_Floating_0                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPickUpItemWI_C::SequenceEvent__ENTRYPOINTPickUpItemWI_0(class UCanvasPanel* Canvas_Floating_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PickUpItemWI_C", "SequenceEvent__ENTRYPOINTPickUpItemWI_0");

	Params::PickUpItemWI_C_SequenceEvent__ENTRYPOINTPickUpItemWI_0 Parms{};

	Parms.Canvas_Floating_0 = Canvas_Floating_0;

	UObject::ProcessEvent(Func, &Parms);
}

}

