#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: RegionSelectedNotificationWI

#include "Basic.hpp"

#include "RegionSelectedNotificationWI_classes.hpp"
#include "RegionSelectedNotificationWI_parameters.hpp"


namespace SDK
{

// Function RegionSelectedNotificationWI.RegionSelectedNotificationWI_C.ExecuteUbergraph_RegionSelectedNotificationWI
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void URegionSelectedNotificationWI_C::ExecuteUbergraph_RegionSelectedNotificationWI(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RegionSelectedNotificationWI_C", "ExecuteUbergraph_RegionSelectedNotificationWI");

	Params::RegionSelectedNotificationWI_C_ExecuteUbergraph_RegionSelectedNotificationWI Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function RegionSelectedNotificationWI.RegionSelectedNotificationWI_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void URegionSelectedNotificationWI_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RegionSelectedNotificationWI_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function RegionSelectedNotificationWI.RegionSelectedNotificationWI_C.OnLogin
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// ELoginRegion                            Region                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void URegionSelectedNotificationWI_C::OnLogin(ELoginRegion Region)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RegionSelectedNotificationWI_C", "OnLogin");

	Params::RegionSelectedNotificationWI_C_OnLogin Parms{};

	Parms.Region = Region;

	UObject::ProcessEvent(Func, &Parms);
}


// Function RegionSelectedNotificationWI.RegionSelectedNotificationWI_C.OnInitialized
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void URegionSelectedNotificationWI_C::OnInitialized()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RegionSelectedNotificationWI_C", "OnInitialized");

	UObject::ProcessEvent(Func, nullptr);
}


// Function RegionSelectedNotificationWI.RegionSelectedNotificationWI_C.Destruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void URegionSelectedNotificationWI_C::Destruct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RegionSelectedNotificationWI_C", "Destruct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function RegionSelectedNotificationWI.RegionSelectedNotificationWI_C.UpdateNotificationText
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// ELoginRegion                            Region                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void URegionSelectedNotificationWI_C::UpdateNotificationText(ELoginRegion Region)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RegionSelectedNotificationWI_C", "UpdateNotificationText");

	Params::RegionSelectedNotificationWI_C_UpdateNotificationText Parms{};

	Parms.Region = Region;

	UObject::ProcessEvent(Func, &Parms);
}

}

